### ISSUE TITLE
Figure out Production/Research dichotomy on Downloads Page

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1020]

**Comment by rileyhgrant** [comment]
Discussed in meeting:
two separate tab groups, top level for version, next level for production / research

![Screen Shot 2022-11-01 at 15 39 38](https://user-images.githubusercontent.com/59549713/199336637-0f4d6a92-e2f9-4ae1-93bf-bec6f501baf5.jpg)

If this is the solution, things become even less searchable from the top level. Users who know what they want to find, and would like to `ctrl f` lose that functionality (currently . This should also be considered and thought about.

**Comment by phildarnowsky-broad** [comment]
What if we did an accordion widget with an "Expand All" instead of tabs?
That way, if you know the dataset you want, "Expand All" makes ctrl-F
feasible again.
