### ISSUE TITLE
Update population/ancestry terms

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1051]
Related to https://github.com/broadinstitute/gnomad_production/issues/707: we received feedback from external users that they prefer to use the term "genetic ancestry" rather than "population" or "ancestry" for clarity

**Comment by mattsolo1** [comment]
Do you suggest we do a global find-and-replace on this term?

**Comment by ch-kr** [comment]
What has the process been in the past for updating terms? This (updating text) was discussed once in the context of updating text about removing samples/relateds with severe disease.

The highest priority changes are the terms on the variant pages and FAQ pages. I think it's fine to leave old blog posts as they were, but we should try to update terminology in new posts

**Comment by mattsolo1** [comment]
Not sure about prior processes. We will focus on the variant pages/FAQ and then make a PR for you to review to make sure the correct instances of these terms have been replaced.

**Comment by rileyhgrant** [comment]
Hiya @ch-kr, we were looking through standing issues during browser meeting and re-looked at this one. 

We wanted to double check, is this something that should be done ahead of v4? It seems it likely is, as v4 from the methods team is probably renaming this with the release of that dataset, unless there's a newer term. 

No rush, but let us know when you have a chance, as it'll help us know whether this should be done in the near-ish future, or if this should be put in the backlog to be done after the v4 release.

**Comment by ch-kr** [comment]
Thank you for checking! Yes, please update all instances of "population" to "genetic ancestry group" prior to/with the v4 release. For example, on the variant pages:
https://gnomad.broadinstitute.org/variant/1-55051215-G-GA?dataset=gnomad_r3
<img width="1212" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/19142091/d5c85ef0-b36b-41aa-9088-a6b87f56f9f4">
the table title "Population Frequencies" should become "Genetic ancestry group frequencies", and the column title "Population" should become "Genetic ancestry group".

Similarly, "popmax" should become "grpmax":
<img width="303" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/19142091/16acdeb6-5c52-4924-93f9-3958116ec30c">
"Popmax Filtering AF" -> "Grpmax Filtering AF"

**Comment by ch-kr** [comment]
One more comment I forgot to add initially -- we are also remaining the "Other" genetic ancestry group as "Remaining individuals" for the v4 release, so this is another term that should get replaced on the variant / FAQ pages
