### ISSUE TITLE
Additional data to optionally show in gene page variant table (and download)

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad-browser#1055]

**Comment by mattsolo1** [comment]
What is the additional data?

**Comment by anneodonnell** [comment]
My initial ticket text did not go through so trying this again. 

There are some additional fields available on the variant page that would be helpful to include as optional fields (in the Configure table menu). 

For gnomAD v2, popmax AF, popmax exome FAF, popmax genome FAF. 

For gnomAD v3 (and v4 when it is added), popmax AF, popmax genome FAF (which will be a combined FAF in gnomAD v4). Also, the in silico predictors (REVEL, CADD, SpliceAI, and PrimateAI). Genomic constraint score might also be nice to have here. 

Users should be able to select which variants to include in the table and when they select “export variants to CSV” it should include these fields, if selected/shown. People ask me fairly frequently to be able to download these data across a gene from the gene variant table on gnomAD.
