### ISSUE TITLE
Add Favicon for the gnomAD browser

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-browser#1071]
Related slack message: https://atgu.slack.com/archives/CNLMF0JLV/p1674904304614369

Add a Favicon to gnomAD.

When users have many open tabs, a Favicon helps them see at a glance which ones are gnomAD.

This could be a single blue peak in the style of the depth of reads chart for a gene/region, or a gnome (not sure if the gnome comment is a joke or not).

**Comment by mattsolo1** [comment]
https://www.npmjs.com/package/favicons-webpack-plugin could be useful here.
