### ISSUE TITLE
Access for gnomAD dataset in aws

### ISSUE THREAD

**Issue by akhilpampana** [broadinstitute/gnomad-browser#1076]
Hello, 

I am trying to access gnomAD public data from aws s3 bucket to load into hail and run an analysis in DNAnexus. It used to work until Friday but I am getting so access timeout errors today. Is there a way to access the files through aws buckets? Thank you so much for your help.

Regards
Akhil

**Comment by sjahl** [comment]
Hi @akhilpampana 

We do have a copy of the gnomAD dataset in AWS's Open Data Sponsorship program: https://aws.amazon.com/marketplace/pp/prodview-z4kk27u6t3nje#resources

The bucket can be found at arn:aws:s3:::gnomad-public-us-east-1 / `s3://gnomad-public-us-east-1`

The data is located in the AWS us-east-1 region, so any compute that you're running in AWS should be located as closely as possible to that region for the best performance.

/cc @ch-kr

**Comment by akhilpampana** [comment]
Hello, 
Thank you so much for the response. I am trying to read the data into hail from DNAnexus and getting a connection timeout error. May I know how to fix this error?
Regards
Akhil

**Comment by akhilpampana** [comment]
This is the error I am getting when trying to read the file through hail from aws cloud bucket through dnanexus

FatalError: ConnectionPoolTimeoutException: Timeout waiting for connection from pool

Java stack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 49 in stage 0.0 failed 4 times, most recent failure: Lost task 49.3 in stage 0.0 (TID 234, ip-10-60-86-40.eu-west-2.compute.internal, executor 0): com.amazonaws.AmazonClientException: Unable to execute HTTP request: Timeout waiting for connection from pool

**Comment by ch-kr** [comment]
Hi Akhil,

Thank you for reaching out to us and for providing the error message. Unfortunately, we are unable to comment on using gnomAD via external platforms; the help team at DNAnexus might be better positioned to look into this error.

**Comment by akhilpampana** [comment]
Thank you so much. I have reached out to them already.  I thought it was a permission issue of some sort so opened the request here.
