### ISSUE TITLE
Test updated SV pipeline against full v3 SVs

### ISSUE THREAD

**Issue by phildarnowsky-broad** [broadinstitute/gnomad-browser#1103]
The full v3 SV dataset is now available. We don't have the histograms yet (hopefully soon), but we can run the rest of the pipeline on the full set to check that there are no surprises up to that point.

**Comment by phildarnowsky-broad** [comment]
Still waiting on the histogram data, but all else seems OK.

**Comment by rileyhgrant** [comment]
Closing this issue as it was moved to `Done` on May 04, 2023
