### ISSUE TITLE
Suggested navbar change: consider other options for "Help" link

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-browser#1121]
At the browser roadmapping meeting, it was suggested that we change the name of the "Help" link in the navbar. Alternative suggestions include: "Info", "Docs & FAQ", and "FAQ". Discussion at the project meeting will follow.

<img width="1253" alt="Info" src="https://github.com/broadinstitute/gnomad-browser/assets/636687/22bbc983-c9d6-4880-bd6c-05963c2ef1f8">
<img width="1250" alt="Docs_and_FAQ" src="https://github.com/broadinstitute/gnomad-browser/assets/636687/7e6adc6d-b9a1-4cbf-ad49-bc1fd3475d7a">
<img width="1229" alt="FAQ" src="https://github.com/broadinstitute/gnomad-browser/assets/636687/057af02d-f9b5-41c7-9e48-33aa0f2ecaf1">
<img width="1229" alt="Help" src="https://github.com/broadinstitute/gnomad-browser/assets/636687/6d9b5c91-aa24-44f3-b24c-82135e63b7d5">

**Comment by rileyhgrant** [comment]
Per this [Slack Thread](https://atgu.slack.com/archives/CNNTF8Z46/p1687290676196959) and reactions to it, the general public of the gnomAD channel voted most strongly in favor of `Help/FAQ`
