### ISSUE TITLE
Update "Report Variant" form

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1123]
The variant report [form](https://docs.google.com/forms/d/1jsaga2MaC1MbygNyx7rNz8dc2mjAb8U1hgA3A9rxbu4/edit) is vague ("Please explain your concern about this variant") and leads to many user inquiries that don't require responses (e.g., someone wrote "Pathogenic, a novel patient" about https://gnomad.broadinstitute.org/variant/2-158630626-C-G?dataset=gnomad_r2_1). Would it be possible to add more text to the variant report to make it clear what the team can or cannot respond to? Something like:
> Note that, for many reasons (including consent and data usage restrictions), we do not have (and cannot share) phenotype information. Overall, we have limited information that we can share for some cohorts, such as last known age in bins of 5 years (when known) and chromosomal sex.

> We wanted to mention another resource that might be of interest. [GenomeConnect](https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.genomeconnect.org%2F&data=02%7C01%7Cjmsavatt%40geisinger.edu%7C5334c63f00ea4f73a65008d845ca1ffc%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637336081708054181&sdata=lDuzguaw9TpcteRodsUnEkvtnxkK%2B73dtTM%2BptXd9rs%3D&reserved=0) is an online registry developed by the [Clinical Genome Resource (ClinGen)](https://clinicalgenome.org/) for people who are interested in sharing de-identified genetic and health information to improve understanding of genetics and health. For anyone who has had genetic testing, you can share your test results. The GenomeConnect team will share the variant(s) with approved users and databases included a large database of clinically interpreted variants, [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/). They also will let you know if the classification has changed by the lab that issued your report if you select to receive updates. GenomeConnect will also allow you to connect with other registrants based on diagnosis, gene, and US State. You can learn more about GenomeConnect [here](https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.clinicalgenome.org%2Fgenomeconnect%2Ffor-patients-genomeconnect%2F&data=02%7C01%7Cjmsavatt%40geisinger.edu%7C5334c63f00ea4f73a65008d845ca1ffc%7C37d46c567c664402a16055c2313b910d%7C0%7C0%7C637336081708064179&sdata=5K0Tb5EWXcai%2FnCTyvkXGpKFdmX12M%2FY77Zvw0HF0ug%3D&reserved=0).

> We are unable to add or remove individual variants from gnomAD.

**Comment by rileyhgrant** [comment]
The google form has been updated with the suggested information, thanks KC for writing this up. I'll plan on closing this issue as completed within a few days if there's no further activity on this front.

![report-variant](https://github.com/broadinstitute/gnomad-browser/assets/59549713/6f0a9ca7-ad35-4fd8-9dc6-bf472809f24c)
