### ISSUE TITLE
Expose VA API via GraphQL

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1132]

**Comment by mattsolo1** [comment]
Schema-related links:

[The revised schema (YAML format)](https://github.com/ga4gh/va-spec/blob/aw-lb-drafting/schema/cohortAlleleFreq.yaml) ([diff](https://github.com/ga4gh/va-spec/compare/9a08cd2863536fd1484e55018156901ee771e188..bf3b5aad51ab19632378babb80706db557363f0f#diff-2c355bba85c0763767d59bbe968fb40fefb3e9e4e44cf3328c5adbd1268e1897))
[The revised example (YAML format)](https://github.com/ga4gh/va-spec/blob/aw-lb-drafting/docs/Modeling/CohortFrequency/simple_result_example.yaml) ([diff](https://github.com/ga4gh/va-spec/compare/9a08cd2863536fd1484e55018156901ee771e188..bf3b5aad51ab19632378babb80706db557363f0f#diff-c5fe931fb813170b68fc5b034c3202cbdf036356545457a1a0f48c738de7a442))
[External validator (JSON format)](https://www.jsonschemavalidator.net/s/12k92fOt)

**Comment by mattsolo1** [comment]
Related info on the VRS REST API: https://github.com/broadinstitute/gnomad-browser-team/issues/43

**Comment by mattsolo1** [comment]
The `gnomad_methods` code provides a clue on what kind of GraphQL arguments we may want to expose to users:

https://github.com/broadinstitute/gnomad_methods/blob/514f634bd4cf31dcdb80a302ac7ba2caeeefffb0/gnomad/resources/grch38/gnomad.py#L530

For now we don't need to support interval queries. Just single variants.

I think the main GraphQL arguments users will be concerned with are `by_ancestry_group` and `by_sex`, so we'll want to expose these. They may also want to be able to specify which specific ancestry groups to return.

**Comment by phildarnowsky-broad** [comment]
One small note on this, since the focus is really on VA data more than VRS, I'm going to start calling this the "VA API" for better clarity.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 am I missing something, or does the REST API not have a way to specify `by_ancestry_group` and `by_sex` parameters?

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 also the data returned by the API doesn't conform to the schema: in particular, it's missing the `type` fields, which we're going to need on the GraphQL end.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 regarding the `type` fields, I did think of a way to work around not having those in the response from the REST API if that's not possible, but it would make things much simpler on this end if we did have them.

**Comment by mattsolo1** [comment]
> does the REST API not have a way to specify by_ancestry_group and by_sex parameters?

Not yet.. I still need to add this (should be straightforward).

> in particular, it's missing the type fields, which we're going to need on the GraphQL end

Didn't realize this was missing; the REST API is passing along everything I'm getting from the hail lookup, so it must not be returned from this. I'll look into why this is.

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 looking more closely, it may only be the top-level VRS object that's missing its `type`, but generally speaking we'll need that anywhere in the data where we have a field that can have one of multiple types--that `type` from the incoming data will eventually determine the `__typename` that GraphQL will put in its responses to disambiguate those types for the client.

**Comment by phildarnowsky-broad** [comment]
Upstream APIs are returning bad data, Dan M. in process of fixing.
