### ISSUE TITLE
Suggestion: autocomplete should be "opt-in" by pressing down arrow

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#1139]
Currently, when a user starts typing to search for a gene, pressing enter will confirm the first autocomplete suggestion.

It might be better if, instead, the user could choose to "opt-in" to the autocomplete results by pressing the down arrow key. This will ensure user is never unexpectedly taken to the wrong search result.

**Comment by rileyhgrant** [comment]
Matt is to check with Mark Daly if this is still an issue, or if #1127 resolved this.

**Comment by rileyhgrant** [comment]
Closing as stale and resolved by #1127
