### ISSUE TITLE
Update external links to DECIPHER

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad-browser#1144]
### What you did:

DECIPHER updated their website link so now gnomAD link (under External resources - and more) isn't going to the right page anymore. 

### What you actually saw after you did that:

Need the Decipher link on the variant page to go to the protein/ genomic page. For example, this [RAD23B]
Decipher link should be https://www.deciphergenomics.org/gene/RAD23B/overview/protein-genomic-info

(it's fine to use the ENSG still - just need to change decipher.sanger.ac.uk to deciphergenomics.org)

**Comment by ch-kr** [comment]
just chiming in to say that I've gotten an email request to fix this also!
> DECIPHER has very recently migrated from the Sanger Institute to
EMBL-EBI. Although Sanger have been supporting the redirection of all
URLs using the web address [decipher.sanger.ac.uk](http://decipher.sanger.ac.uk/) for the last 2 years,
they are now only re-directing to the homepage
(https://deciphergenomics.org/). A DECIPHER user has alerted me that the
links in gnomAD are no longer re-direction correctly as they are using
the [decipher.sanger.ac.uk](http://decipher.sanger.ac.uk/) URL, can these links please be updated to use
https://deciphergenomics.org/?
