### ISSUE TITLE
Re-order links on Nav Bar, adjust titles

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-browser#1149]
Currently, the order of the links on the gnomAD browsers navigation bar is: 
- About, Team,  News, Changelog, Downloads, Policies, Publications, Contact, Help

![Screenshot 2023-08-04 at 14 06 40](https://github.com/broadinstitute/gnomad-browser/assets/59549713/02c5324a-ba5c-4443-91af-be4bb3296769)

Based on their relative popularity, the order should be changed to: 
- About, Team, Policies, Publications, News (to be changed to Blog), Changelog, Downloads, Help/FAQ.

In addition, the link for "News" should be changed to say "Blog"

This will require a change on the gnomAD Blog as well as on the gnomAD Browser, to keep the two in sync.

**Comment by mattsolo1** [comment]
@lamrhoang we are happy to accept pull requests
