### ISSUE TITLE
Updating GCS path to phased HGDP+1kGP haplotypes

### ISSUE THREAD

**Issue by LindoNkambule** [broadinstitute/gnomad-browser#1151]
Hi gnomAD Team,

We have a new version (utilized pedigree information to improve phasing) of the phased HGDP+1kGP haplotypes. Katherine (@ch-kr) is in the process of copying the phased haplotypes to the public gnomAD GCS bucket and asked if you could update the [download link paths](https://gnomad.broadinstitute.org/downloads#v3-hgdp-1kg-tutorials) on the gnomAD browser once she'd done copying the files. The update will be from `gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes` to `gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2` for GCS path.

Thanks,
Lindo

**Comment by ch-kr** [comment]
The new files have been synced to GCP and AWS:
```
gs://gcp-public-data--gnomad/resources/hgdp_1kg/phased_haplotypes_v2
s3://gnomad-public-us-east-1/resources/hgdp_1kg/phased_haplotypes_v2
```
I just copied the files to AWS today, so they should be available in Azure on ~Monday
