### ISSUE TITLE
Add text about spliceAI licensing

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1170]
We discussed adding text about spliceAI's licensing at a project meeting earlier this year (3/21). Here is the proposed text to add to the [Policies page](https://gnomad.broadinstitute.org/policies) (under Terms of use):

> Some annotations may have restrictions on usage. For instance, SpliceAI annotations have been computed by Illumina and are provided with permission under a CC BY NC 4.0 license for academic and non-commercial use https://github.com/Illumina/SpliceAI. It is the responsibility of users to abide by all relevant licensing requirements.

Konrad and Heidi have also proposed this update to the first sentence of the third paragraph on the Terms of use.
Current sentence:

> The data released by gnomAD are available free of restrictions under the [Creative Commons Zero Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/).

Proposed edit:
> The primary data from the gnomAD exomes and genomes are available free of restrictions under the [Creative Commons Zero Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by elissa-alarmani** [comment]
This looks great! One question I had, do we also want to edit that same sentence in the [general FAQ](https://gnomad.broadinstitute.org/help#general): "What are the restrictions on data usage?" 
> The data released by gnomAD are available free of restrictions under the [Creative Commons Zero Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) .
