### ISSUE TITLE
issue with "display nearby variants" search

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/gnomad-browser#1191]
### What you did: I tried searching for a variant, using the p. nomenclature (e.g. 
p.Arg8Leu in DNAH11), in the variant table on the gene page and deselected the "display nearby variants" box. I was looking for a variant that was at the same position but has a different amino acid change (e.g. p.Arg8Tyr). I just deleted some of the original search criteria in the search bar and the browser changed to display the "something went wrong" page. The same thing happened when i redid the first step and just started typing something different into the search bar that didn't match anything that existed in the table. This could just be when I typed an error into the search bar as well.

 
Trying to find a variant that did not exist using the gnomAD gene page search in the variant table.
https://gnomad.broadinstitute.org/gene/ENSG00000105877?dataset=gnomad_r2_1

### What you expected to see after you did that:

I expected to see no matching variant in the variant table but not the error page.

The gene page would be there with a note of no matching variants in the variant table.

### What you actually saw after you did that:

I saw the something went wrong page (screenshot attached). 
![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/d707a092-a17b-4816-b734-31685a98259f)

**Comment by rileyhgrant** [comment]
This should be fixed now @msingerb, just deployed a tiny patch.

Thanks for bringing this to our attention, and for the detailed description of how to replicate the error you were seeing, that's super helpful!
