### ISSUE TITLE
Upgrade Node.js version

### ISSUE THREAD

**Issue by singhsum-nih** [broadinstitute/gnomad-browser#1211]
Hello, we wanted to see if you had any plans of updating Node in the near future to the active LTS release, node.js v18.  To support Dr. Les Biesecker’s lab at NHGRI, we set up a local instance of the gnomAD browser to display variants from ~15,000 exome and genome samples to the NIH community.  The current version of Node in the gnomAD browser, v14, was end of life in April, but we can continue to run it under RHEL/CentOS 7 until June 2024. After that date, as per HHS security policies, we will need to move to CentOS9, which does not support v14 of Node. We anticipate that there will be compatibility issues when we move to CentOS9 and the newer version of Node, and wanted to check with you before we tried to update to the code base on our end.

**Comment by sjahl** [comment]
@singhsum-nih Yes, there is currently an effort underway to modernize the toolchain, including a nodejs upgrade, in #1198

**Comment by singhsum-nih** [comment]
@sjahl Thank you very much for the response, this is very helpful.  Do you have an ETA in mind for this effort?

**Comment by sjahl** [comment]
We have a higher priority project underway at the moment, but I suspect that this will not be too far from the top of our stack after the first week of November or so. I'd like to think it'll be done by the end of the year -- most certainly we'll have it released before your centos EOL date in June
