### ISSUE TITLE
Display bug on variant pages

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-browser#1234]
Could be other pages too, but i noticed this on the v4 variant page: The Gene page button overlaps with the variant title

![Screenshot 2023-10-31 at 5 23 23 PM](https://github.com/broadinstitute/gnomad-browser/assets/636687/5cfbcedc-ec07-4d74-a4af-24c98d1f24d5)

The copy variant ID button is also missing.

**Comment by rileyhgrant** [comment]
Resolved by #1232
