### ISSUE TITLE
Incorrect units on the downloads page

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-browser#1262]
We've gotten one or two reports that some the size units on the downloads page are incorrect -- they are listed in MiB, but should be GiB. The reports we've seen so far reference chr13, chr18, and chr21

![screenshot_2023-11-03_at_1 27 36_pm](https://github.com/broadinstitute/gnomad-browser/assets/636687/15e680d1-5399-44a5-b369-8d9089fead7a)

**Comment by elissa-alarmani** [comment]
chr13 is already GiB, is that what it should be, or should it be changed to MiB?

**Comment by sjahl** [comment]
> chr13 is already GiB, is that what it should be, or should it be changed to MiB?

@elissa-alarmani Looks like GiB is correct for chr13 when I try to download it

**Comment by rileyhgrant** [comment]
Resolved by #1264
