### ISSUE TITLE
RSID disambiguation broken in v4

### ISSUE THREAD

**Issue by phildarnowsky-broad** [broadinstitute/gnomad-browser#1266]
Apparently due to error in API. Example: http://localhost:8008/variant/rs328?dataset=gnomad_r4

**Comment by rileyhgrant** [comment]
Looks like Matt's PR (#1268) fixed it.

![Screenshot 2023-11-08 at 13 37 22](https://github.com/broadinstitute/gnomad-browser/assets/59549713/7ac9d83d-b28c-45ab-9df0-edf46187fb7a)

**Comment by rileyhgrant** [comment]
Fix is in prod.

https://gnomad.broadinstitute.org/variant/rs328?dataset=gnomad_r4
