### ISSUE TITLE
chrY vcf download info are missing for gnomad v4 genomes

### ISSUE THREAD

**Issue by weixuanfu** [broadinstitute/gnomad-browser#1267]
### What you did:

I cannot see the [download](https://gnomad.broadinstitute.org/downloads) info for chrY in gnomad v4 genomes but it is available for exomes callset.  The urls for chrY are valid but only missing in the frontend UI.
https://storage.googleapis.com/gcp-public-data--gnomad/release/4.0/vcf/genomes/gnomad.genomes.v4.0.sites.chrY.vcf.bgz
https://storage.googleapis.com/gcp-public-data--gnomad/release/4.0/vcf/genomes/gnomad.genomes.v4.0.sites.chrY.vcf.bgz.tbi

Please see the screenshot attached herein. I found this issue in Safari and Chrome in macOS 13.6.
<img width="842" alt="Screen Shot 2023-11-07 at 11 25 22 AM" src="https://github.com/broadinstitute/gnomad-browser/assets/21084970/1edf7d84-bceb-46c7-bdba-094cee6c8c2a">

**Comment by rileyhgrant** [comment]
Thanks for filing this issue! Just opened a short PR to fix it, this should get merged and deployed in relatively short order.
