### ISSUE TITLE
"Export variants to CSV" button not working for some proteins

### ISSUE THREAD

**Issue by tekpinar** [broadinstitute/gnomad-browser#1283]
Hi,
I am trying to download gnomad v4.0.0 data for KCNQ1 protein. I did the research from the search bar and I found the following page: 

https://gnomad.broadinstitute.org/gene/ENSG00000053918?dataset=gnomad_r4

I went down and clicked on "Export variants to CSV" button but it doesn't work. It doesn't download anything. 

I tested it with Brave v159.124 and Firefox v119 on Ubuntu 22.04. 

For some other proteins, "Export variants to CSV" button worked when I deselected "Other" or "pLof" options just above the button but it doesn't work for this particular case. 

I was wondering if you can take a look to this bug.
Thanks,
Mustafa

**Comment by mattsolo1** [comment]
I just tried downloading the CSV for this gene and it worked.  I think it was resolved by #1274 (cc @rileyhgrant).

@tekpinar could you please let us know if it is working now?

**Comment by tekpinar** [comment]
Hi,
I was able to download the file. 
Thanks,
Mustafa

**Comment by rileyhgrant** [comment]
Awesome, happy to hear it was resolved Mustafa!

Closing this as completed by #1274
