### ISSUE TITLE
MD5 check FAILED: gnomad.genomes.v4.0.sites.chrY.vcf.bgz

### ISSUE THREAD

**Issue by booorange** [broadinstitute/gnomad-browser#1298]
Hi

I have downloaded the gnomAD v4 dataset, the MD5 check for the file gnomad.genomes.v4.0.sites.chrY.vcf.bgz failed, both at Google and Amazon links.

![image](https://github.com/broadinstitute/gnomad-browser/assets/142484288/36279646-b118-47c8-9acb-0124f834f573)

**Comment by rileyhgrant** [comment]
Heya @booorange,

Thanks for filing this issue! Our apologies for this, we have a PR open that will update the checksum on the website shortly.

For the moment, the correct checksum should be:

```
gsutil hash -h gs://gcp-public-data--gnomad/release/4.0/vcf/genomes/gnomad.genomes.v4.0.sites.chrY.vcf.bgz

Hashes [hex] for release/4.0/vcf/genomes/gnomad.genomes.v4.0.sites.chrY.vcf.bgz:
	Hash (md5):		8c231b75745b6670555915847c9999e8
	Hash (crc32c):		4b5875ee
```

Feel free to look at https://github.com/broadinstitute/gnomad-browser/pull/1296 for more context.
