### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by dbolser** [broadinstitute/gnomad-browser#1299]
The gnomAD v4.0.0 README link on this page:
https://gnomad.broadinstitute.org/downloads#v4-variants

is broken.

It points here:
https://storage.googleapis.com/gcp-public-data--gnomad/release/4.0/README.txt

Which gives some kind of fancy 404 ;-)

**Comment by rileyhgrant** [comment]
Hiya, thanks for filing this issue!

This was my bad, we actually don't have a README, favoring the [blog post](https://gnomad.broadinstitute.org/news/2023-11-gnomad-v4-0/) instead. This link will be removed from the site since a README doesn't exist.

Thanks!
