### ISSUE TITLE
Remove link to v4.0 README

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1302]
The downloads page currently points users to a README file explaining v4.0:
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/fb3ea82f-91e9-4ecf-889a-2d03fcb96c6f)
However, this file does not exist. Could we update the text to only point users to our blog post, similar to the text for the v3 downloads?
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/fe67ff43-0c18-4fd3-ad2e-0403ef7ce110)

**Comment by rileyhgrant** [comment]
Resolved by #1300
