### ISSUE TITLE
mismatched v4 variant data between downloaded file and web-displayed info

### ISSUE THREAD

**Issue by glennm51** [broadinstitute/gnomad-browser#1307]
</style>
</head>

<body link="#0563C1" vlink="#954F72">

16 | 2089662
-- | --

</body>

</html>

* For concerns about data, check the frequently asked questions
  (https://gnomad.broadinstitute.org/help#frequently-asked-questions) or
  send an email to gnomad@broadinstitute.org.

-->

**Comment by glennm51** [comment]
https://gnomad.broadinstitute.org/variant/16-2089662-G-A?dataset=gnomad_r4

data does not match what is found when downloading variants for an entire gene

**Comment by glennm51** [comment]
[gnomAD_v4.0.0_ENSG00000008710_2023_11_17_10_34_57.csv](https://github.com/broadinstitute/gnomad-browser/files/13395625/gnomAD_v4.0.0_ENSG00000008710_2023_11_17_10_34_57.csv)


<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GLENNA~1.MAS/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GLENNA~1.MAS/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Chromosome | Position | rsIDs | Reference | Alternate | Source | Filters - exomes | Filters - genomes | Transcript | HGVS Consequence | Protein Consequence | Transcript Consequence | VEP Annotation | ClinVar Clinical Significance | ClinVar Variation ID | Flags | Allele Count | Allele Number | Allele Frequency | Homozygote Count | Hemizygote Count | Allele Count Remaining | Allele Number Remaining | Homozygote Count Remaining | Hemizygote Count Remaining | Allele Count Admixed American | Allele Number Admixed American | Homozygote Count Admixed American | Hemizygote Count Admixed American | Allele Count European (Finnish) | Allele Number European (Finnish) | Homozygote Count European   (Finnish) | Hemizygote Count European   (Finnish) | Allele Count Middle Eastern | Allele Number Middle Eastern | Homozygote Count Middle Eastern | Hemizygote Count Middle Eastern | Allele Count European   (non-Finnish) | Allele Number European   (non-Finnish) | Homozygote Count European   (non-Finnish) | Hemizygote Count European   (non-Finnish) | Allele Count South Asian | Allele Number South Asian | Homozygote Count South Asian | Hemizygote Count South Asian | Allele Count Ashkenazi Jewish | Allele Number Ashkenazi Jewish | Homozygote Count Ashkenazi Jewish | Hemizygote Count Ashkenazi Jewish | Allele Count East Asian | Allele Number East Asian | Homozygote Count East Asian | Hemizygote Count East Asian | Allele Count African/African   American | Allele Number African/African   American | Homozygote Count African/African   American | Hemizygote Count African/African   American
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
16 | 2089662 | rs557909051 | G | A | gnomAD Exomes,gnomAD Genomes | PASS | PASS | ENST00000262304.9 | c.*65C>T |   | c.*65C>T | 3_prime_UTR_variant |   | 389 | 1533642 | 0.000254 | 0 | 0 | 21 | 59270 | 0 | 0 | 0 | 50866 | 0 | 0 | 8 | 57582 | 0 | 0 | 0 | 4962 | 0 | 0 | 302 | 1072110 | 0 | 0 | 14 | 79038 | 0 | 0 | 3 | 29870 | 0 | 0 | 10 | 39018 | 0 | 0 | 17 | 72884 | 0 | 0



</body>

</html>

**Comment by glennm51** [comment]
Apologies, I thought i typed this up when i first opened the issue but it disappeared.  I have found yesteday and today that when you download a file of variant data for an entire gene, the data in that file for specific values does not match the data shown on the web page for the same variant.  specifically the East asian, south asian, middle eastern, european non-finnish allele count and or allele number do not match for any given variant between the download and the website, although the total AC and AN do match and the remaining, african, and admixed american and finnish do match. this has been seen in 3 different genes, myh7, pkd1 and cep290.

**Comment by rileyhgrant** [comment]
Adding link to Slack thread to keep info in one place: https://atgu.slack.com/archives/CNL7NA6H2/p1700496608050559

**Comment by rileyhgrant** [comment]
Thanks for filing this issue @glennm51, sorry for the confusion. I will start to look into this tomorrow. 

Also, thanks so much for the detailed description -- it's much appreciated.
