### ISSUE TITLE
Update v2 RMC download links

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1313]
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/b58fd369-8317-4411-a020-b7d1ce9ac121)

The current [RMC downloads](https://gnomad.broadinstitute.org/downloads#v2-regional-missense-constraint) only have GCP links. Would it be possible to:

- Update HT links to include the option to show/copy links (similar to the [v2 gene constraint HT](https://gnomad.broadinstitute.org/downloads#v2-constraint))rather than only having the option to download the v2 RMC HT?
- Add links to the AWS and Azure versions of these data?

**Comment by rileyhgrant** [comment]
Ah, yep, good catches on both fronts as always. Thanks for filing this issue!
