### ISSUE TITLE
Variant appears to be failing genomes on gene page but passes on variant page

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/gnomad-browser#1321]
### What you did:
I searched for a specific variant from the search bar (22-20037009-TG-T) in gnomAD v4 after finding it first in gnomAD v2.1.1 (22-20024532-TG-T).

I was viewing the variant in v2 and wanted to see if it was in v4. I clicked the link that connects them and found the variant. When I went back to the v4 gene page and searched the variant in the variant table, it came up as not passing quality filters in both exomes and genomes. The variant page indicated it DID pass filters in genomes only.

v2 variant page: https://gnomad.broadinstitute.org/variant/22-20024532-TG-T?dataset=gnomad_r2_1
v4 variant page: https://gnomad.broadinstitute.org/variant/22-20037009-TG-T?dataset=gnomad_r4
v4 gene page: https://gnomad.broadinstitute.org/gene/ENSG00000183597?dataset=gnomad_r4

### What you expected to see after you did that:

I expected to see the variant in the table and it not to have been flagged for low quality in both exomes and genomes since it passed QC in genomes.

The variant would be seen in the variant table on the gene page and would not be shown to have failed genomes and exomes within the variant table.

### What you actually saw after you did that:

I saw that the variant was there but was shown to have failed QC in exomes and genomes.

I can see the variant but the quality metrics from the variant page do not match what is shown in the variant table on the gene page.

![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/0fac1cd0-6331-4822-b6e4-92a1d6eec3c4)
![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/03cbf53f-bf1c-4ea2-b5cb-db6a9274b52f)

**Comment by rileyhgrant** [comment]
Thanks for filing this issue @msingerb and for the detailed description, it's super helpful :)

Related Slack thread: https://the-tgg.slack.com/archives/C018PB68VU5/p1701182967740059

We should have a fix for this in relatively short order.
