### ISSUE TITLE
Access to `variant_cooccurrence_counts.py`  input files

### ISSUE THREAD

**Issue by ignatiusm** [broadinstitute/gnomad-browser#1328]
This is a data question - I did send an email as per the issue template guidance, but I see you are doing active development on `genes` pipeline, so I thought I'd cheekily ask here too. Apologies for cross-posting :grimacing: 

I am working through the `genes` pipeline. Thanks for updating the GTEx and pext paths @rileyhgrant . A subsequent step in the pipeline uses `variant_cooccurrence_counts.py` which references to input data files assigned to `TWO_HET_DATA_PATH` and `HOMOZYGOUS_DATA_PATH`. These files are stored in the `gs://gnomad-browser-data-pipeline` bucket which doesn't have public access. Do you know if these files are able to be shared, or if they are able to be found in one of the other public buckets? I've had a good hunt through the manifests etc, but have not had any luck.

**Comment by rileyhgrant** [comment]
Ah great question and great catch as per usual.

Not sure if the production team has responded to the email, but I can respond here. Pretty much this is a goof by us, we'll get that data synced to the public bucket where the rest of the shared data is stored, and can get those links added to the downloads page once they're up.

We can also respond here when we get those files in the public bucket, as updating the downloads page may lag a little bit behind the files actually being made public.

**Comment by ignatiusm** [comment]
Amazing - thank you very much! I totally understand that there is a LOT involved in a new data release. Really appreciate your help.

**Comment by ignatiusm** [comment]
Whoop! Thanks @rileyhgrant !
