### ISSUE TITLE
Clicking on gnomAD SVs v4 from STR page leads to error

### ISSUE THREAD

**Issue by bw2** [broadinstitute/gnomad-browser#1336]
Starting from https://gnomad.broadinstitute.org/short-tandem-repeat/HTT?dataset=gnomad_r4
and clicking 
<img width="419" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/6240170/f21ac63e-ddc8-4682-88c8-a15576d506db">

leads to https://gnomad.broadinstitute.org/short-tandem-repeat/HTT?dataset=gnomad_sv_r4

<img width="1135" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/6240170/b82119ef-5204-423e-bf15-1af4d7e7192f">

**Comment by mattsolo1** [comment]
Somewhat related to this issue: @bw2 would it be appropriate to add STRs as a v4 dataset under the SV (righthand side) in the dropdown menu?

![image](https://github.com/broadinstitute/gnomad-browser/assets/8867295/0169366b-dab1-4996-9456-5c57559ee291)

**Comment by bw2** [comment]
Yes, I think so!

**Comment by bw2** [comment]
We should call it TRs (ie. tandem repeats) rather than STRs (short tandem repeats) since we include some loci with motifs longer than 6bp. 
What would the user see after clicking on this new "gnomAD TRs v4.0" link?
