### ISSUE TITLE
Load mitochondrial constraint metrics to the mito gene pages

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1339]
Nicole Lake has reached out to us requesting that we load her mitochondrial constraint metrics into the browser. The current plan is to invite her to present her metrics to the project at a gnomAD project meeting in early 2024 before finalizing whether we want to work on this task, but I'm opening this ticket now so that you are aware that this could be coming down the pipe.

More details here: https://docs.google.com/presentation/d/1K-WbjLythLcmoYgHESaeKF5Jz26GnXZRNg_erhzmj2M/edit?usp=sharing

**Comment by rileyhgrant** [comment]
Closing in favor of #1409
