### ISSUE TITLE
Add link to forum to Report Variant form

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1351]
Users are still occasionally using this form (see https://docs.google.com/spreadsheets/d/1NXrLrsq_3sz_Sp1NoS1ZL3qta8BIRoSyjEdxJ_sJc2k/edit?resourcekey#gid=1191389100). Would it be possible to add a link to the forum to the form? This is the text we currently have in our email autoreply:

>Please refer to our [forum](https://discuss.gnomad.broadinstitute.org/) and our [FAQ](https://gnomad.broadinstitute.org/help) page to see if your question has previously been answered. In general, we prioritize responding to questions on our [forum](https://discuss.gnomad.broadinstitute.org/) over questions received via email; consider posting your question on the forum if you would like a response.

**Comment by rileyhgrant** [comment]
Added the text from the auto reply to the description of the report variant form, to hopefully divert some users to the forum or FAQ if they have a question that can be answered more generally than by using this form.

![Screenshot 2023-12-18 at 13 27 13](https://github.com/broadinstitute/gnomad-browser/assets/59549713/4ca211a4-dc0f-4e4e-abbc-ed2916495e3c)
