### ISSUE TITLE
STR pages no longer show read data ("Unable to load read data" error message)

### ISSUE THREAD

**Issue by bw2** [broadinstitute/gnomad-browser#1356]
STR pages no longer display read data. For example, 

https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN1?dataset=gnomad_r4
https://gnomad.broadinstitute.org/short-tandem-repeat/EIF4A3

Scrolling to the bottom shows

<img width="957" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/6240170/9ce09850-f248-44f8-bea3-50b9dcfc6acf">

Console shows 500 error on request to https://gnomad.broadinstitute.org/reads/:

<img width="1792" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/6240170/1b69c182-2262-4c05-9b5a-371a9dc7676c">

**Comment by bw2** [comment]
Just realized the images work @
https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN1?dataset=gnomad_r3
but not 
https://gnomad.broadinstitute.org/short-tandem-repeat/ATXN1?dataset=gnomad_r4

**Comment by rileyhgrant** [comment]
Hey @bw2,

We were looking over the triage board in browser meeting and saw this issue. Is this an issue that you had filed with the intention of coming back to work on yourself? Or is this something that you had filed with the intent of one of us on the browser team resolving this.

Matt had mentioned that you had possibly filed some issues that you were going to circle back to, so we wanted to check.

Thanks!

**Comment by bw2** [comment]
Hey @rileyhgrant,

Thanks for checking. I don't have a server dev environment or a way to investigate production server-side errors so would appreciate if you guys could look into this.

**Comment by rileyhgrant** [comment]
Great, thanks for the clarification.
