### ISSUE TITLE
STR pages that don't have a link to "External Resources / STRipy" should still show the "Related Loci / All pathogenic short tandem repeats in gnomAD" link

### ISSUE THREAD

**Issue by bw2** [broadinstitute/gnomad-browser#1357]
Most STR pages correctly have "External Resources" and "Related Loci" sections at the top. For example
https://gnomad.broadinstitute.org/short-tandem-repeat/ATN1?dataset=gnomad_r4
<img width="365" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/6240170/a48ee4b1-d62f-4d35-ad0e-1b1af93f355a">

Some STR pages correctly don't display the "External Resources" section - for example:
https://gnomad.broadinstitute.org/short-tandem-repeat/VWA1?dataset=gnomad_r4

However, these pages without an "External Resources" section should still display the "Related Loci" section so users can get back to the table of all STR loci, but this currently doesn't happen. Pages without the "External Resources" section for some reason also drop the "Related Loci" section:

https://gnomad.broadinstitute.org/short-tandem-repeat/VWA1?dataset=gnomad_r4
https://gnomad.broadinstitute.org/short-tandem-repeat/PRNP?dataset=gnomad_r4
https://gnomad.broadinstitute.org/short-tandem-repeat/EIF4A3?dataset=gnomad_r4
https://gnomad.broadinstitute.org/short-tandem-repeat/CSTB?dataset=gnomad_r4

[All pathogenic short tandem repeats in gnomAD](https://gnomad.broadinstitute.org/short-tandem-repeats?dataset=gnomad_r4)

**Comment by rileyhgrant** [comment]
Hey @bw2,

We were looking over the triage board in browser meeting and saw this issue. Is this an issue that you had filed with the intention of coming back to work on yourself? Or is this something that you had filed with the intent of one of us on the browser team resolving this.

Matt had mentioned that you had possibly filed some issues that you were going to circle back to, so we wanted to check.

Thanks!

**Comment by bw2** [comment]
Hey @rileyhgrant,

Thanks for checking. I will post issues for things that I think make more sense for the core browser team to tackle (include this) and just submit PRs where I can.

**Comment by rileyhgrant** [comment]
Perfect, thanks for the clarification
