### ISSUE TITLE
bcftools +split-vep -s worst; Too few columns at chr1:69059 .. 1 (Consequence) >= 1

### ISSUE THREAD

**Issue by robertzeibich** [broadinstitute/gnomad-browser#1360]
I will just link to the post I have just made: https://github.com/samtools/bcftools/issues/2057

The VEP information fields in the header (n=46) do not match the information fileds in the body (n=48) of the VCF file.

**Comment by rileyhgrant** [comment]
Hiya @robertzeibich 

Thanks for filing this issue. This appears to be an issue with the dataset, as opposed to the browser which is primarily used to navigate this dataset. 

As such, we'd recommend creating a topic on our [Discourse forum](https://discuss.gnomad.broadinstitute.org/), where the production team can better answer your question.
