### ISSUE TITLE
The same number of variants from two groups of gnomAD

### ISSUE THREAD

**Issue by MaryGoAround** [broadinstitute/gnomad-browser#1381]
Hi
 
 
Having statement from gnomAD team

**The controls subset has people who we know where controls for whatever the study was recruiting for (e.g. a control in a type 2 diabetes study) and anyone from a biobank, so both of those categories may include people with cancer. The non-cancer subset excludes the TCGA cohort (there are germline samples from TCGA in gnomAD v2 but not in v4).** 
 
 
I extracted mutations in regulatory coordinates of an oncogen from `gnomAD non_cancer_nfe` AND `gnomAD biobanks_nfe` , independently but I got the same number of mutations in _both_ of `gnomAD non_cancer_nfe` AND `gnomAD biobanks_nfe`.
 
I have not been able to figure out how I got the same number of mutations from `16k controls_and_biobanks_nfe` and `74K non_cancer_nfe`
 
Any idea please?
 
Thank you in advance.

**Comment by rileyhgrant** [comment]
Hey @MaryGoAround 

Thanks for filing this issue! As this appears to be something relating more to the gnomAD dataset itself, and less the browser, is it possible to redirect your question to our forum? https://discuss.gnomad.broadinstitute.org

The forum includes members of the gnomAD methods team that are closer to the creation of the data, and are better equipped to answer your question. Thanks!

**Comment by rileyhgrant** [comment]
Closing this issue since as mentioned above, this is better suited to the forum.
