### ISSUE TITLE
v2 gene page CSV export displaying incorrect column info

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-browser#1393]
Per this [Slack Thread](https://atgu.slack.com/files/USLACKBOT/F06EG6VH18X/csv_download_issue_for_adcy10_and_agxt), the v2 downloads appear to be showing the 'afr' set of columns twice, and skipping some other columns.

I am the one who most recently touched this logic, I can likely take a look at this some time this week since it's meeting free week.

Related #1055

**Comment by gm-bee** [comment]
Hi, just wondering if there's an estimate of when this issue would be fixed? We rely on these downloads for an internal process and can't move forward w/o it.

**Comment by rileyhgrant** [comment]
Hiya @gm-bee 

Sorry to have blocked you for this amount of time. I'm planning on merging and deploying the PR this morning. 

For v2 this fixes the `afr` group showing up twice incorrectly, replacing the duplicate `afr` set of columns with the `amr` (admixed american) columns as intended. It also adds a few new columns to the v2 download: gnomad ID then 4 columns about groupmax AF and genetic ancestry group for exomes and genomes in v2.

I'll be merging and deploying those changes this morning, definitely reach out if things are still unsatisfactory, and thanks for your patience.

- Riley

**Comment by rileyhgrant** [comment]
This has been merged and deployed, closing this issue as resolved. Please reach out if you see any further issues.

**Comment by michellepaczosa** [comment]
Thank you for your work resolving this!
