### ISSUE TITLE
regional variants error in gnomad v4

### ISSUE THREAD

**Issue by mikespiller1** [broadinstitute/gnomad-browser#1408]
### What you did:

searching gnomad v4 by regional co ordinates, eg:
https://gnomad.broadinstitute.org/region/1-2228855-2228895?dataset=gnomad_r4

### What you expected to see after you did that:

List of variants in this region

### What you actually saw after you did that:

"An unknown error occurred", below the coverage data, where the variant tracks and list would normally be displayed.

![Annotation 2024-02-07 120630](https://github.com/broadinstitute/gnomad-browser/assets/54353137/8083dcf0-8a56-4a27-940f-5f93b5e3c6cc)

**Comment by rileyhgrant** [comment]
Hiya! Thanks for filing this issue.

This was resolved by #1411.

Apologies for the inconvenience.
