### ISSUE TITLE
Add new flag to variants page when variant is not called in one data type

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1423]
Very long context:
Variants that are only present in one data type (exomes or genomes) currently only display frequencies in a single data type. For example:
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/d3cb416b-5da6-48b7-9c8e-fea52edd9a8a)
https://gnomad.broadinstitute.org/variant/2-151663543-C-T?dataset=gnomad_r4
only shows frequency information from the v4 exomes because this variant was not called in the v4 genomes. Given the genomes coverage in this region:
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/60a0c738-b09c-404c-8fd2-bd6f4765e6ff)
the most likely reason why this variant doesn't have any allele number (AN) information from the genomes is due to the fact that we do not joint call our two data types into a single callset (we have separate exomes and genomes callsets). This means that the v4 genomes likely all had homozygous reference genotype calls at this locus, so this variant was not emitted in that callset (despite it being present in 7 exome samples). 

The team is working on a new type of computation that generates AN across all possible sites for both data types. Once we have created this new releasable file, we will be able to incorporate new AN information to variants that previously only had frequency information from one data type but have good coverage in the other data type (such as 2-151663543-C-T above).

Request:
After we update the ANs / joint frequencies, I would like to update this "No variant" to make it very clear when a variant was truly not seen / not possible to have been detected / zero AN in either the exomes or genomes. My current idea is to add a hover over to the "No variant" box explaining this, something like:

> This variant was not called in the gnomAD <data type>; no samples had any genotype call (no samples had reference or alternate calls).

Would it be possible to add this new hover over text and share a screenshot/demo with the wider project to get feedback?

**Comment by mattsolo1** [comment]
Should be easy to add this when the flag is there. If this is just an addition of hover text I'm not sure if we need much in the way of screenshots other than just figuring the text should say?

**Comment by ch-kr** [comment]
yep, I was thinking that it would be nice to share the screenshots with the internal project to get feedback and make sure people understand what what the flag is designed to convey before releasing publicly
