### ISSUE TITLE
Add number of samples in v4.0 subsets to stats page

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1440]
Would it be possible to add the number of samples in the v4.0 exomes subsets (UKB, non-UKB) to the browser? https://docs.google.com/spreadsheets/d/1Nql3eV1WpOwrtjdegNL9pC-5KiYImpvDhHUvLEvmGik/edit#gid=0

**Comment by mattsolo1** [comment]
Are you talking about after we add UKB to the browser? Or is this a stats page update?

**Comment by ch-kr** [comment]
oof sorry I didn't write very much in the initial post -- this is a request to add a table to the stats page to show how many samples are in each subset of the v4 exomes. We're planning to release the allele number across all called sites as part of the next minor release, so having a quick way for users to look up how many samples exist in each subset will be really handy when they look at the AN for variants called only in Broad-specific or UKB-specific capture regions (will help them understand what number they should expect for a high callrate site)
