### ISSUE TITLE
Adding hemizygous counts in variant table on gene page for gnomAD SV's

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/gnomad-browser#1462]
For all gene pages we have the option to configure the variant table and see how many homozygous/hemizygous individuals there are for a single variant. It is incredibly helpful to show the number of hemizygous individuals for X-linked genes in particular. The hemizygous individuals are the ones that are male and carry a single copy of the variant on the X-chromosome. This information is currently provided for the normal browser, but not for the SV browser. I am asking for it to be added as a viewable option in the configure options for the variant table on the gene page for the SV browser. The photos below show it as an option in the normal browser and missing from the SV browser. This information is stored in the individual variant pages for SV's (see screenshot), but not viewable on the gene pages. This makes it impossible to easily filter to variants that have been seen in hemizygosity across the gene. Instead we have to open every variant page in the gene to determine the zygosity of the variant.

![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/4454ec73-d127-4fe1-a223-87c4bac4d66d)
![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/9ea2e12f-661a-4bc6-b0fc-69386f16401a)
![image](https://github.com/broadinstitute/gnomad-browser/assets/47390031/07073e52-b8d6-4627-8705-82f34eeda640)

**Comment by phildarnowsky-broad** [comment]
Hi @msingerb , this should be working in production now. Thanks for bringing it to our attention, and have a nice weekend!
