### ISSUE TITLE
New hover over text for "No variant" flag

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1498]
It would be helpful to add hover over text to the "No variant" flag to help differentiate it from the AC0 flag. Proposed text:

Variant is not present in this data type. All defined sample genotypes from this data type are homozygous reference.

**Comment by KoalaQin** [comment]
Would you also want it to be more accurate? Like: 
Variant is not present in this data type. All high quality genotypes from this data type are homozygous reference.
Since we filtered to adj?

**Comment by mike-w-wilson** [comment]
I think the addition of high quality could be confusing since `All high quality genotypes from this data type are homozygous reference.` defines AC0 precisely

**Comment by ch-kr** [comment]
let's stick with the original text because the point of this hover over text is to differentiate between "No variant" and "AC0". you're right, Qin, that the genotypes are filtered to adj, but technically, all genotypes are homref, which is why the locus wasn't retained in prior gnomAD versions / added until we calculated AN across all callable sites

**Comment by KoalaQin** [comment]
Oh okay, I just found "all defined sample genotypes" unclear.

**Comment by ch-kr** [comment]
do you have another wording suggestion? happy to change if you have a clearer wording

**Comment by KoalaQin** [comment]
What do you mean by "defined sample genotypes"? Non-missing? I don't have strong opinion on this and not an expert on wording. Isn't "all genotypes" enough?

**Comment by ch-kr** [comment]
how about this:

Variant is not present in this data type. All called sample genotypes from this data type are homozygous reference.

**Comment by KoalaQin** [comment]
LGTM!
