### ISSUE TITLE
Export to CSV not working for larger genes

### ISSUE THREAD

**Issue by tweston10** [broadinstitute/gnomad-browser#1508]
### What you did:

I am running pipelines for which I query gnomAD using Ensembl gene/transcript IDs, by automated CSV export using the buttons on the main site. I have noted for the past couple of weeks that for the large gene I am working on (TTN), clicking on this button does not have the desired effect, but that all other variant table properties work as expected.

Page in question: [https://gnomad.broadinstitute.org/gene/ENSG00000155657?dataset=gnomad_r4](https://gnomad.broadinstitute.org/gene/ENSG00000155657?dataset=gnomad_r4)

### What you expected to see after you did that:

On clicking the "Export variants to CSV" button a dialog opens for saving the CSV locally, including all variants associated with this gene ID, as is the case at present on other gene pages.

### What you actually saw after you did that:

On clicking the "Export variants to CSV" button there is no response from the site, nor any indication of background tasks, nor any result from waiting.

**Comment by rileyhgrant** [comment]
Hiya @tweston10 

Thanks for bringing this to our attention, we will work on fixing this -- we actually very specifically treat TTN differently than all the other genes because of its size.

Are there any other large genes that this export to CSV is not working on for you, or is it specifically and only for TTN? Knowing whether or not its just TTN would be helpful for us to fix this bug.

Thanks for your patience, 

Riley

**Comment by tweston10** [comment]
Hi @rileyhgrant, thanks for the quick response

I can confirm that, for "Export to CSV" functionality, the two other large proteins obscurin (OBSCN) and nebulin (NEB) are working as intended (with minor delay), so this specific problem seems to be unique to titin.

Some further details that may be relevant are that, while I can "Export to CSV" for OBSCN and NEB, any attempt to retrieve variants for transcripts of these proteins produces an error ("Unable to load variants"). This issue does not appear to be relevant for smaller proteins (tested with PIK3CA). I mention this as I note that the browser is specifically prevented from retrieving variants for specific TTN transcripts at present ("Due to the size of TTN, the variant table is temporarily unavailable in the browser or API for transcripts") and possibly there is a connection to the Export to CSV issue.

Additionally, the "Export to CSV" was working for me after the rollout of gnomAD version 4.0, and I noticed the issue prior to the introduction of version 4.1 last week, if this helps to narrow down a time frame.

Many thanks,

Timir Weston

**Comment by rileyhgrant** [comment]
Thanks for the additional info! This is very helpful.

We probably need to treat those other large genes like we treat TTN, the "Unable to load variants" message in this case is likely because we're trying to return so many variants we hit a timeout -- v4 increased the size of our data a lot.

**Comment by rileyhgrant** [comment]
Hiya @tweston10,

Sorry for the inconvenience. I'm working on figuring out what's going on in production causing these, for transparency -- I regenerated the cache used specifically for TTN, and was able to load the variants and get the CSV in a local instance of the browser, but some difference in production is causing the cache not to successfully load in that environment.

That said, I do have the .csv file, if its helpful for me to get that to you somehow in the meantime while we debug this issue, let me know. 

Thanks for your patience with this

**Comment by tweston10** [comment]
Hi @rileyhgrant,

Thank you for the update - I was slightly confused I think when I saw the issue marked as closed, and wanted to report the new status of the titin pages

I would appreciate the CSV if it is not too much trouble to move it (I know it is quite sizeable) just to check for allele frequency differences against 4.0.0

Many thanks,

Timir Weston

**Comment by rileyhgrant** [comment]
Heya again @tweston10,

Yeah apologies about the issue having been closed, I thought it had been resolved by the other PR, and the merging of that PR auto-closed this issue.

That said, a few members of the browser team got on a call and worked out a solution to get TTN loading in production, I just double-checked, and the variants for TTN are loading on V4, and I'm able to download the `.csv` file as expected. So hopefully that means we can cut out the middleman and you can just grab the `.csv` directly!

Thanks for your patience and helpful information, and don't hesitate to post here or in a new issue if anything still seems off.

- Riley

**Comment by tweston10** [comment]
Hi @rileyhgrant,

I can confirm that the CSV download is working for titin on Chrome, Firefox, Opera and Edge. Thank you for all of your help with this.

Many thanks,

Timir Weston
