### ISSUE TITLE
v4.1 Genomes Chr2 sites MD5

### ISSUE THREAD

**Issue by everkinderen** [broadinstitute/gnomad-browser#1511]
Hello, 

It seems like the MD5 for the Genomes chr2 sites VCF in new v4.1 was not updated in the Downloads page, it's still showing the checksum for the v4.0 VCF. The MD5s of the other chromosome VCFs have been updated.

Thanks in advance for fixing this.

**Comment by rileyhgrant** [comment]
Hiya @everkinderen,

Thanks for filing this issue! My apologies, I did indeed miss this one. We'll have this corrected on the downloads page shortly, in the meantime, in case you're blocked by not being able to confirm a checksum, the correct value should be `518ca01e6757a68bc0abe76f85af644d`

Thanks,

Riley
