### ISSUE TITLE
Use the friendlier component for hail table URLs on the downloads page

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/gnomad-browser#1520]
It seems like some, but not all, of our hail table links on the download page pop up this friendly component that encourages people to download objects using one of the object store clients: 

<img width="802" alt="Screenshot 2024-04-25 at 3 59 02 PM" src="https://github.com/broadinstitute/gnomad-browser/assets/636687/d3968a31-9c06-415d-b223-e5f31020202f">

We're not using this component on at least the Joint Frequency table, the result being, when we link people to the HTTPS URL for a hail table, they'll always get a 404 even when the link is correct.

Could we ensure that all of the hail table links on the downloads page are using this popup component?

**Comment by sjahl** [comment]
references of confusion caused:
- https://discuss.gnomad.broadinstitute.org/t/gnomad-v4-1-0-joint-sites-hail-table-download-results-in-404/262/5?u=steve
- #1519

**Comment by rileyhgrant** [comment]
Closed by #1521
