### ISSUE TITLE
Update notes about local ancestry frequencies

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1546]
The local ancestry inference notice text looks like this:
<img width="1223" alt="image" src="https://github.com/broadinstitute/gnomad-browser/assets/19142091/63b13f6b-9791-41f3-a3f1-8cc5f146f003">
from https://gnomad.broadinstitute.org/variant/9-114195977-G-C?dataset=gnomad_r4

I'd like to request two updates to the text:
- Remove reference to "Latino" from "Note Local ancestry data is available for this variant by selecting the tab below. See our blog post on [local ancestry inference for Latino/Admixed American samples in gnomAD](https://gnomad.broadinstitute.org/news/2021-12-local-ancestry-inference-for-latino-admixed-american-samples-in-gnomad/) for more information."
- Update "populations" to "genetic ancestry groups" in "Note Local ancestry is not available for all gnomAD populations."

**Comment by rileyhgrant** [comment]
Resolved by #1548
