### ISSUE TITLE
CNV region example text

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/gnomad-browser#1584]
### What you did:

I clicked on the example CNV region on the [home page](https://gnomad.broadinstitute.org/): [19-11078371-11144910](https://gnomad.broadinstitute.org/region/2-49918501-51225575?dataset=gnomad_cnv_r4)

### What you expected to see after you did that:
I expected this to bring me to a region on chromosome 19

### What you actually saw after you did that:

The link brought me to a region on chromosome 2: https://gnomad.broadinstitute.org/region/2-49918501-51225575?dataset=gnomad_cnv_r4
![image](https://github.com/broadinstitute/gnomad-browser/assets/19142091/2210de3b-6ca2-4443-b30e-ec253b630977)

If this is the intended behavior, could someone update the text in the link on the home page from `19-11078371-11144910` to `2-49918501-51225575`?

**Comment by sjahl** [comment]
hey @ch-kr -- I think the link text (or, the link target) is just incorrect, rather than anything intentional.

Do you have a preference for whether we should link to the `2-` or `19-` region from the home page? I'll make it point to 19 if not, since that's what people think they've been clicking on, I suppose.

**Comment by sjahl** [comment]
For context, the SV link right above it points to that same 19- region... so my guess is that the original intention was to link to 2-, maybe that's a better choice.

**Comment by ch-kr** [comment]
I'll double check with Jack and update here

**Comment by ch-kr** [comment]
Jack proposed we point to PCSK9: https://gnomad.broadinstitute.org/region/1-55039447-55064852?dataset=gnomad_cnv_r4
