### ISSUE TITLE
Render error on /variant/2-169132617-A-G

### ISSUE THREAD

**Issue by dcweeks** [broadinstitute/gnomad-browser#1637]

**Comment by phildarnowsky-broad** [comment]
Hi @dcweeks , I had a look at this page and didn't see anything clearly wrong with it, do you have any more details about what you saw?

**Comment by dcweeks** [comment]
Yes it appears OK to me now too. 

Seems like the page started to render but then failed — the start of rendering content went away  to some message encouraging one to report it.  Sorry I didn’t have a chance to add more info at the time but I was in a hurry.

I’m trying to remember but I think it cleared after I restarted the browser (chrome on macOS) and tried again.

**Comment by rileyhgrant** [comment]
Thanks for filing this issue,

Since we cannot replicate this, and it appears OK now to you, we believe this was a transient error, and will close this issue.

Thanks!
