### ISSUE TITLE
Add links to AFR LAI VCFs on downloads page

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/gnomad-browser#1640]
The AFR LAI VCF has synced to the public buckets:

GCS: gs://gcp-public-data--gnomad/release/4.1/local_ancestry/genomes/gnomad.genomes.v4.1.local_ancestry.afr.vcf.bgz
S3: s3://gnomad-public-us-east-1/release/4.1/local_ancestry/genomes/gnomad.genomes.v4.1.local_ancestry.afr.vcf.bgz 

This relates to this work: https://github.com/broadinstitute/gnomad-browser-team/issues/72

KC asked these public paths to be 4.1 so I think they should be in the v4 downloads section and could we mimic this AMR blurb?
![Screenshot 2024-10-10 at 8 47 37 AM](https://github.com/user-attachments/assets/0619f0a9-b968-4909-a4be-9f99b011575a)

The associated blog post is here: https://github.com/broadinstitute/gnomad-blog/pull/173

**Comment by rileyhgrant** [comment]
Closed by #1638
