### ISSUE TITLE
Header information for the list of constrained genes.

### ISSUE THREAD

**Issue by dantaki** [broadinstitute/gnomad-browser#416]
Where can I find a detailed description of the column names for the gnomAD list of constrained genes? 

For example: what is the difference between `oe_lof_upper_bin` and `oe_lof_upper_bin_6`?

Doing a google search on the terms results in literally nothing. From my own calculations I can guess that `oe_lof_upper_bin` are the deciles for the oe_lof_upper scores, which the maximum oe_lof_upper score is 0.27.

However, the maximum oe_lof_upper score for the first decile for oe_lof_upper_bin_6 is 0.37 which is close to the 0.35 value in the gnomAD blog post. 

So can we get a clarification on the column names please?

**Comment by dantaki** [comment]
Sorry, `oe_lof_upper_bin_6` are sextiles. Makes sense. But can we still get a README for this document please?

**Comment by nawatts** [comment]
Hi @dantaki,

A README for the gene constraint data is on the todo list.

**Comment by nawatts** [comment]
Hi @dantaki,

Descriptions of the fields in the constraint metrics files can be found on pages 74-77 of the supplementary information for the paper [*The mutational constraint spectrum quantified from variation in 141,456 humans*](https://www.biorxiv.org/content/10.1101/531210v4).

The Supplementary Information PDF can be downloaded from https://www.biorxiv.org/content/10.1101/531210v4.supplementary-material

The long term goal of adding this information to the browser for all data files is tracked in #103.
