### ISSUE TITLE
GRCh38 version of pext?

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#447]

**Comment by nawatts** [comment]
Won't be available for the initial release of v3 in the browser. Check to make sure the browser UI handles nothing returned for pext.

**Comment by nawatts** [comment]
This is blocked until GTEx and gnomAD are both on the same version of Gencode. Currently, GTEx v8 is on Gencode 26 and gnomAD v3 is on Gencode 29.

**Comment by jon4thin** [comment]
still has not been completed?

**Comment by jon4thin** [comment]
Is there a GRCh38 version of pext for gnomAD v2.1.1 liftover?

**Comment by rileyhgrant** [comment]
Resolved by #1602
