### ISSUE TITLE
RFC: add MANE and RefSeq transcripts to the gnomAD browser

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#518]
This proposal relates to a suggestion from Heidi that gnomAD adopt the MANE transcript as the canonical transcript. 

From the website [MANE transcript website](https://useast.ensembl.org/info/genome/genebuild/mane.html):

> During phase 1, we will release the MANE Select transcript set to include one well-supported transcript per protein-coding locus. All transcripts in the set will perfectly align to the GRCh38 reference assembly and represent 100% identity (5’UTR, CDS, 3’UTR) between the Ensembl (ENST) transcript and the corresponding RefSeq (NM) transcript.
 
I’m not sure when this transcript set will be released, but wanted to make sure we consider this in the future.

Heidi also mentioned that it would be extremely useful for clinical geneticists to have [RefSeq transcripts](https://www.ncbi.nlm.nih.gov/projects/genome/guide/human/index.shtml) searchable and plotted in the gnomAD browser. Perhaps there could be a toggle option on the gene page. What technical challenges are associated with this?

**Comment by nawatts** [comment]
The changes to replace canonical transcripts with MANE Select transcripts are done.

* MANE Select transcript shown in gene info
* MANE Select transcript highlighted in transcripts track
* Consequence in non-MANE Select transcript highlighted in variant table (the sort order of transcript consequences still doesn't take MANE Select into account, but that will be fixed for v4)
* MANE Select transcript consequence highlighted in annotations section of variant page
