### ISSUE TITLE
Include transcript version numbers on variant page

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#526]
Include version numbers in the Ensembl IDs shown in the annotations section of the variant page.

These are not present in VEP annotations on variants, so they will have to be pulled from the Gencode data that corresponds to the variant dataset.

Also need to handle fetching these from gene models for all variants in a gene/region/transcript at once for #517.

**Comment by deannachurch** [comment]
I would like to second this request. I'm trying to reconcile things with ClinVar and I would have more confidence if I had transcript versions.
