### ISSUE TITLE
Flag genes where pext shouldn't be used 

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#529]
For some genes where pext is low throughout, pext scores should not be used for variant interpretation. These genes should be flagged and a warning shown near the pext track.

@berylc @msingerb what should the condition for this flag be?

**Comment by nawatts** [comment]
List of genes: gs://gnomad-public/papers/2019-tx-annotation/data/GRCH37_hg19/max_pext_low_genes.021520.tsv

Warning text:
> For this gene, RSEM assigns higher expression to non-coding transcripts than protein coding transcripts, which likely represents an artifact in the isoform expression quantification, and results in all protein coding variants in the gene to have a low value.

**Comment by msingerb** [comment]
I'm good with that warning message.
