### ISSUE TITLE
Join exome and genome data before loading into Elasticsearch

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#530]
Currently, exome and genome data for variants and coverage is stored in separate indices. For variants, this results in storing duplicate copies of several fields (including transcript consequences). It also makes queries more complicated. These should be joined together in the data loading pipeline.

**Comment by mattsolo1** [comment]
Fun fact: this was my first ever assigned issue, but never accomplished. https://github.com/macarthur-lab/gnomad_browser/issues/1

Good luck! 😃

**Comment by nawatts** [comment]
Resolved in 0bbe1e73711c5f92cebd8f4fc8d8a8b2790fee99.
