### ISSUE TITLE
Add clinical significance column to variant table

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#553]
For variants that appear in ClinVar, show their clinical significance in the variant table.

This column should also include a flag for zero star variants.

**Comment by mattsolo1** [comment]
Can't remember -- did we discuss the option of adding clinical significance information to the Flags columns instead of creating a new column?

**Comment by nawatts** [comment]
It was discussed in the Google Doc. Clinical significance isn't in the same category as flags, which are generally warnings about a low quality site or questionable annotations. @heidirehm proposed the separate column.
