### ISSUE TITLE
gnomAD browser launch 

### ISSUE THREAD

**Issue by GenomicsPrograms** [broadinstitute/gnomad-browser#561]
I followed the installation instructions on the github webpage:
https://github.com/broadinstitute/gnomad-browser

I typed:
cd projects/gnomad
yarn start

and got the following:

**user-linux:~/gnomAD/gnomad-browser/projects/gnomad$** yarn start
Usage Error: Couldn't find a script named "webpack-dev-server".

$ yarn run [--inspect] [--inspect-brk] <scriptName> ...

I searched the gnomAD github and couldn't find the script: webpack-dev-server

**Comment by nawatts** [comment]
Hi @GenomicsPrograms,

To install dependencies, run `yarn` or `yarn install` from root directory of the gnomad-browser repository.

**Comment by GenomicsPrograms** [comment]
Hi @nawatts 
I tried that and got a verbose output, here is the tail end:

                                              ^~~~~~~~~~~~
node_sqlite3.target.mk:131: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: Leaving directory '/home/mlinan/gnomad-browser/node_modules/sqlite3/build'
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/mlinan/gnomad-browser/node_modules/sqlite3/lib/binding/node-v79-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/mlinan/gnomad-browser/node_modules/sqlite3/lib/binding/node-v79-linux-x64" "--napi_version=6" "--node_abi_napi=napi"
gyp ERR! cwd /home/mlinan/gnomad-browser/node_modules/sqlite3
gyp ERR! node -v v13.11.0

**Comment by GenomicsPrograms** [comment]
Never mind, I just tried yarn start and it worked! :)

**Comment by nawatts** [comment]
The [sqlite](https://www.npmjs.com/package/sqlite) package is only used by the `gnomad-reads` service, so you should be able to run most of the browser without it.
