### ISSUE TITLE
Replacing the gnomAD data sets with mine

### ISSUE THREAD

**Issue by GenomicsPrograms** [broadinstitute/gnomad-browser#562]
Hi - 
I downloaded the gnomAD browser from the github and launched it on my desktop.
How do I replace the browser data with my own?

**Comment by nawatts** [comment]
The [Query](https://github.com/broadinstitute/gnomad-browser/blob/master/projects/gnomad/src/client/Query.js) component is where the browser's front end connects to the gnomAD API to fetch data. You could modify that component (and/or components that use Query) to fetch data from your own web service.
