### ISSUE TITLE
Different results on same search

### ISSUE THREAD

**Issue by ejarh** [broadinstitute/gnomad-browser#569]
I used the link from Alamut to get to the right variant site in gnomAD. The first search resulted in "Variant not found" (https://gnomad.broadinstitute.org/variant/19-10939832-C-T). However, as there were frequencies in Alamut from gnomAD, I retried it and got to the site where the variant is present in 74 alleles in total (https://gnomad.broadinstitute.org/variant/19-10939832-C-T (the same link as before)). 
This is not the first time we have seen this discrepancy in gnomAD. 
  
![1](https://user-images.githubusercontent.com/63781371/79437919-242d5880-7fd3-11ea-8de4-55b4f4c40ce7.png)
![2](https://user-images.githubusercontent.com/63781371/79437939-28f20c80-7fd3-11ea-9807-3850efa1b838.png)

**Comment by nawatts** [comment]
When querying Elasticsearch for a variant or other data, it looks like we are not handling the case where ES may return partial results.

This can happen when some shards fail or timeout. ES 6.3 added an [`allow_partial_search_results` option](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/search-request-body.html) to consider partial results a failure. The version we use does not support this, but we should be able to use the `_shards` field in the search response to check for partial failures.

**Comment by nawatts** [comment]
Assuming the issue is caused by partial search failures in Elasticsearch, 772d4a51bffaf79ec6630fa5e30b0417bb22b8aa should resolve it.
