### ISSUE TITLE
Error running yarn start on linux

### ISSUE THREAD

**Issue by mamtagiri** [broadinstitute/gnomad-browser#570]
Hi guys,

I had local version running on Mac with no problems. I tried to do the same on a remote linux- and I keep getting a long running list of errors.

I tried to resolve any missing module but this seems something else.

Can anyone please help:

Many thanks!!
Mamta

below is just a part of it.

ℹ ｢wds｣: Project is running at http://localhost:8008/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/mamta/gnomad-browser/projects/gnomad
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: 
ERROR in ./src/client/Main.js
Module not found: Error: Can't resolve '@gnomad/help' in '/home/mamta/gnomad-browser/projects/gnomad/src/client'
 @ ./src/client/Main.js 16:0-49 22:8-25
 @ ./src/client/index.js

**Comment by nawatts** [comment]
Hi @mamtagiri,

The `@gnomad/help` package is contained in the `gnomad-browser/packages/help` directory. It's made available to the browser package using [yarn workspaces](https://classic.yarnpkg.com/en/docs/workspaces/).

Did you run `yarn` in the top-level `gnomad-browser` directory?

**Comment by mamtagiri** [comment]
Yes, I did and it seemed all fine. This happened only at the yarn start under projects/gnomad

(MamtaTest) (base) mamta@avi:~/gnomad-browser$ yarn
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.03s.

**Comment by nawatts** [comment]
I haven't been able to reproduce this. I'd guess maybe some issue related to symlinks.

You might be able to work around it by adding
```
'@gnomad/help': path.resolve(__dirname, '../../../packages/help')
```
to [`resolve.alias` in the webpack configuration](https://github.com/broadinstitute/gnomad-browser/blob/5b87de7a50488e03fafd18c65970fbc7d45973b5/projects/gnomad/config/webpack.config.client.js#L78-L82).

**Comment by mamtagiri** [comment]
ok thanks!

But the problem doesn't seem like only @gnomad/help but a long long running list of error.
So Iam assuming it might be something else?

1. Could this be because I used npm as my package manager (I also tried npm start and get other bunch of errors)

2. Could the linux machine have issues with the port ?

Thanks for looking into it! Appreciate it

**Comment by nawatts** [comment]
I would expect

**Comment by mamtagiri** [comment]
Ok. Just removed and git cloned the repo again and it worked!
Thanks Nick!

**Comment by nawatts** [comment]
Excellent, glad you were able to find a solution.
