### ISSUE TITLE
Extracting cohorts from gnomAD VCF

### ISSUE THREAD

**Issue by ricardoharripaul** [broadinstitute/gnomad-browser#572]
### What you did:
I downloaded the exome VCF file from the downloads page https://gnomad.broadinstitute.org/downloads and realized all cohort subsets (controls, non-cancer, non-neuro, and non-TOPMed) were included in a single VCF file.  I would like to do some statistics on the controls and non-neuro subsets but I am not sure how to extract the variants.

**Comment by nawatts** [comment]
Hi @ricardoharripaul,

The VCFs include INFO fields for allele count, allele number, allele frequency, etc. in each subset (controls_AC, non_neuro_AF, etc).

You could use [bcftools](http://www.htslib.org/doc/bcftools.html) to filter the VCFs down to only variants that have AC > 0 in the desired subset.

```
bcftools filter -i 'INFO/controls_AC[0] > 0' /path/to/gnomad.vcf.bgz --output /path/to/filtered.vcf.gz --output-type z
```

Alternatively, you could use [Hail](https://hail.is/docs/0.2/index.html) and the Hail Table versions of gnomAD to do the filter.

**Comment by ricardoharripaul** [comment]
Hi Nick,

Thanks.  That works.

Best,

Ricardo
