### ISSUE TITLE
Pre-computed annotations (not expression data)

### ISSUE THREAD

**Issue by GenomicsPrograms** [broadinstitute/gnomad-browser#578]
Regarding the gnomAD browser, I need the regular pre-computed annotations for all human genes (as in their browser csv export), not the expression data as is listed on the gnomAD downloads page.

Where can I obtain this data?

**Comment by nawatts** [comment]
All variant information shown in the gnomAD browser can be downloaded in Hail Table or VCF format from the locations listed on https://gnomad.broadinstitute.org/downloads#v2-variants and https://gnomad.broadinstitute.org/downloads#v3-variants.
