### ISSUE TITLE
Add option to download the full list of pLoF variants from Konrad's paper

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#585]

**Comment by gtiao** [comment]
pLoF variant list is available here: https://gnomad.broadinstitute.org/downloads. Request reference: https://atgu.slack.com/archives/CNL7NA6H2/p1591626047080100

**Comment by nawatts** [comment]
This was done August 4th in 94c3c64a448e17b2c28cb93f72b29415066dbe2a.

https://gnomad.broadinstitute.org/downloads#v2-resources

https://atgu.slack.com/archives/CNL7NA6H2/p1596568126188000?thread_ts=1591626047.080100&cid=CNL7NA6H2
