### ISSUE TITLE
Review help content

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#596]
Review and possibly update help content for:

* [Dataset selection](https://github.com/broadinstitute/gnomad-browser/blob/ea34e247386262617a78b5aedb8e7509c7be58a0/projects/gnomad/src/client/help/content/dataset-selection.md)
* [Variant QC](https://github.com/broadinstitute/gnomad-browser/blob/ea34e247386262617a78b5aedb8e7509c7be58a0/projects/gnomad/src/client/help/content/variant-qc.md)
* [Relatedness filtering](https://github.com/broadinstitute/gnomad-browser/blob/ea34e247386262617a78b5aedb8e7509c7be58a0/projects/gnomad/src/client/help/content/relatedness-filtering.md)
* [Annotations in gnomAD](https://github.com/broadinstitute/gnomad-browser/blob/ea34e247386262617a78b5aedb8e7509c7be58a0/projects/gnomad/src/client/help/content/vep.md)

**Comment by ytarasov-broad** [comment]
Also add explainer on controls subset?

**Comment by nawatts** [comment]
We have some information about subsets in the help popup next to the dataset menu. Maybe we can elaborate on the descriptions there.

https://github.com/broadinstitute/gnomad-browser/blob/master/projects/gnomad/src/client/help/content/dataset-selection.md

**Comment by nawatts** [comment]
Resolved in 049e01c74a2e6906403c514c136454dcb26be244.
