### ISSUE TITLE
When Ref allel does not show up in GnomadV3, 0 frequency of Alt reported?

### ISSUE THREAD

**Issue by EugeneEA** [broadinstitute/gnomad-browser#602]
Dear Gnomad team, I'v already asked this question on biostars (https://www.biostars.org/p/458734/#460285) and also drop an email to gnomad@broadinstitute.org some time ago but newer get a response (

shortly:
there is an snp https://www.biostars.org/p/458734/#459297
with an alt allele frequency of 9.99979e-01 according to gnomadv2 exomes 
BUT it is absent in gnomadv3 genomes which clearly is not true (it just can not be possible given the alt frequency close to 1). 

I'll apreciate some clarification, couse I need to understand the data limitations to build the pipline I'm developing accodingly! 
Thanks for your efforts and best wishes, Eugene Albert

**Comment by nawatts** [comment]
Hi @EugeneEA,

It looks like the reference sequence changed between GRCh37 and GRCh38.

In gnomAD v2, rs142200057 is an insertion (2-31805880-A-AG) and the reference sequence starting at 2-31805880 is AGGCTT
https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr2%3A31805880%2D31805885

In GRCh38, the reference sequence starting at the equivalent coordinate (2-31580810) is AGGGCTT
https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2%3A31580810%2D31580816

Thus, this sequence identified would not be called as a variant in gnomAD v3.

**Comment by EugeneEA** [comment]
Hi @nawatts thanks - that does indeed escape my attention and that does explain why there is no insertion in this position in gnomadV3. 

Also I'd like to point out that this rises the other issue: if mapping was done on GRCh37 first, it is virtually imposible to liftover .vcf file to GRCh38 correctly (meaning to destinguish how many G are in that position). And indeed if you'll look up rs142200057 in the gnomadV2 liftover file (https://storage.googleapis.com/gnomad-public/release/2.1.1/liftover_grch38/vcf/exomes/gnomad.exomes.r2.1.1.sites.2.liftover_grch38.vcf.bgz) you'll find that this SNP has frequency of AF=9.99979e-01 - and now (in GRCh38) imply the genotype GGGG, which is stil not true ;) 

So actually GnomadV2 **AND** gnomadV3 shows correct frequencies of correct genotypes 9.99979e-01 of GGG and 0 of GGGG respectively (each for their own build) **BUT** GnomadV2_liftover demonstrates wrong frequency of 9.99979e-01 for GGGG.

And probably this is why in ClinVar all frequency of major genotype (GGG) are low (switched with minor GGGG)
https://www.ncbi.nlm.nih.gov/snp/rs142200057

Best, Eugene

**Comment by nawatts** [comment]
> Is my interpretation correct?

I couldn't say. I'm not a bioinformatician and am out of my depth here.

Generally though, the gnomAD v2 liftover is known to be imperfect and is intended as a stopgap until a GRCh38 exome dataset is produced.
https://gnomad.broadinstitute.org/faq#when-are-exomes-going-to-be-available-on-grch38
