### ISSUE TITLE
UI error - colocatedVariants required

### ISSUE THREAD

**Issue by mhebrard** [broadinstitute/gnomad-browser#611]
Hi, I would suggest to edit the line below

https://github.com/broadinstitute/gnomad-browser/blob/cc021a0a2aa436ea8524c3d70e878083e8721245/projects/gnomad-api/src/schema/datasets/gnomad_r3/fetchGnomadV3VariantDetails.js#L126

to:

```colocatedVariants: variant.multiallelic_variants || [], ```

to avoid the React error message below, in case the field dont exists.

```Warning: Failed prop type: The prop `variant.colocatedVariants` is marked as required in `VariantPageContent`, but its value is `null`.```

**Comment by nawatts** [comment]
Do you have an example of a variant where this is occurring? That field should always contain an array.

**Comment by mhebrard** [comment]
as of gnomad v3, I see that colocated variants are directly present in Elasticsearch DB.
I am working on a in-house dataset that was generated previously based on gnomad repos, but do not contain the colocated variants.
In my case, colocated variants is null. to fit with gnomad borwser I turn it as empty ...

looking further, I see that for gnomad v2.1 do not have this field in the DB but you query the DB to the variant specific position. WOuld you advice to follow v2.1 ? i.e. query the BD for the current position then return empty if nothing is found, instead of my solution that was defaulting the field as empty.
