### ISSUE TITLE
Is there a coverage file for the liftover gnomAD v2 GRCh38?

### ISSUE THREAD

**Issue by Antoine-Fav** [broadinstitute/gnomad-browser#614]
Hello gnomAD team,

I have been working with gnomAD v2 GRCh37 exome files, including the TSV coverage file.
I am planning on switching to GRCh38 by using your liftover version, however, there is no TSV coverage file associated. Do you have one available somewhere? Alternatively, if I convert the GRCh37 TSV file to GRCh38 will it be consistent with the VCFs?

Thank you in advance for your help!

**Comment by nawatts** [comment]
Hi @Antoine-Fav,

We don't have a lifted over coverage file available. The [liftover functions](https://broadinstitute.github.io/gnomad_methods/api_reference/utils/liftover.html) in [broadinstitute/gnomad_methods](https://github.com/broadinstitute/gnomad_methods) may be useful in producting one.
