### ISSUE TITLE
Add v2 LD matrices to downloads page

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#615]

**Comment by nawatts** [comment]
@konradjk what are the URLs for these files?

**Comment by konradjk** [comment]
It's all under `gs://gnomad-public-requester-pays/release/2.1.1/ld` (not sure where it is in the hosted area but presumably that follows the structure?)

**Comment by nawatts** [comment]
How many of these files should be listed?

For each population, there are:
* `<pop>.common.adj.ld.bm`
* `<pop>.common.adj.ld.variant_indices.ht`
* `<pop>.common.ld.bm`
* `<pop>.common.ld.variant_indices.ht`
* `scores/<pop>.ld_scores.ht`
* `scores/<pop>.adj.ld_scores.ht`
* `scores/<pop>.adj.ld_scores.M`
* `scores/<pop>.adj.ld_scores.M_5_50`
* `scores/<po>.adj.ld_scores.ldscore.bgz`

And there are some files in scores with combinations of two populations.

**Comment by konradjk** [comment]
We can borrow aspects from Masa's description of these for pan-ancestry: https://github.com/atgu/ukbb_pan_ancestry/pull/25/files#diff-bb9888b88c055b6e263dff85c64ff2163e396daa54ebbf7681653ecd57810c18R319

The two population ones were custom cuts that don't really need to be documented but we could.
