### ISSUE TITLE
Update About Us Page

### ISSUE THREAD

**Issue by ytarasov-broad** [broadinstitute/gnomad-browser#616]
Update to add/remove PIs, contributing projects, etc.
Needed changes are in this sheet:
https://docs.google.com/document/d/1pcu5Y4kt80rduj7PbAkqqYrnlL9BGfpfzztEmEedgP8/edit#

**Comment by nawatts** [comment]
Resolved in 163c1d4bbdca30cf4f12cc5a9e3e5c57b888d390.
