### ISSUE TITLE
Add descriptions for v3.1 site quality metrics

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#619]
There are not currently descriptions for any of the allele-specific metrics in v3.1.

https://github.com/broadinstitute/gnomad-browser/blob/37b70191e15b4b9e0f6c5ca7d4c8a071795c7f13/projects/gnomad/src/client/VariantPage/qualityMetrics/qualityMetricDescriptions.js#L2-L22

Also need to show different description for SiteQuality based on dataset. SiteQuality is AS_QUALapprox in v3.1 and qual in v2.

**Comment by nawatts** [comment]
The current descriptions are taken from https://github.com/broadinstitute/gnomad_methods/blob/bfcb7756ab309f593108be82dd351adf56f81558/gnomad/utils/vcf.py#L121-L156

Should the `AS_*` metrics use the same descriptions? Or prefixed with "Allele-specific"?

@jkgoodrich

**Comment by jkgoodrich** [comment]
prefixed with "Allele-specific"
