### ISSUE TITLE
Hide readviz by default?

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#633]
BAI files for v3.1 are very large (~6 MB) and more than one may be loaded for a variant. Consider hiding the reads data section by default to avoid downloading so much data when it may not be needed.

Ideally, there should be an option to always show readviz to support users that frequently look at reads.

**Comment by sjahl** [comment]
Throwing this in triage for discussion. We spend $1200/month in egress bandwidth, and the overwhelming majority is data sent out from the reads backend.

**Comment by ch-kr** [comment]
I like the idea of hiding reads by default given the cost associated with displaying these data. Also, as we move into the federated scheme, we also won't have read data available for all displayed/loaded variants.

Having an option to always display reads would partially solve this problem, but I imagine some subset of users would choose to always show reads even if they don't actually look at them that often. I propose we poll our internal stakeholders for their opinions, and if not enough people have opinions, hide the reads by default (and see if users start writing in about this behavior)
