### ISSUE TITLE
Blog Page is missing

### ISSUE THREAD

**Issue by GenomicsPrograms** [broadinstitute/gnomad-browser#656]
When I launch the gnomAD browser in my linux env, there is no content in the blog page. 
All I see is: 

Page Not Found
This page does not exist. Try searching for a gene, region, or variant or go to the home page.

How do I get this to work so that I can start adding my own content to the blog?

Here is my Yarn output, when I type it in the gnomad-browser folder:

root@DESKTOP-DND2RRS:/mnt/c/Users/User1/gnomad-browser# yarn
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @hot-loader/react-dom@16.13.0" has unmet peer dependency "react@^16.0.0".
warning " > @testing-library/react@10.4.3" has unmet peer dependency "react@*".
warning " > @testing-library/react@10.4.3" has unmet peer dependency "react-dom@*".
warning " > babel-plugin-styled-components@1.10.7" has unmet peer dependency "styled-components@>= 2".
warning " > react-hot-loader@4.12.21" has unmet peer dependency "react@^15.0.0 || ^16.0.0".
warning " > react-hot-loader@4.12.21" has unmet peer dependency "react-dom@^15.0.0 || ^16.0.0".
[4/4] Building fresh packages...
[-/5] ⢀ waiting...
[-/5] ⢀ waiting...
[-/5] ⢀ waiting...
[-/5] ⢀ waiting...
error /mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@15.2.1 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@15.2.1 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v88-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.2.1 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.2.1 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/15.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/15.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/15.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@15.2.1 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
/bin/sh: 1: python: not found
make: Leaving directory '/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/build'
make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/nodejs/bin/node" "/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/lib/binding/node-v88-linux-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd /mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3
gyp ERR! node -v v15.2.1
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/nodejs/bin/node /usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/lib/binding/node-v88-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/lib/binding/node-v88-linux-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/mnt/c/Users/User1/gnomad-browser/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:329:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1055:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/local/nodejs/bin/node" "/mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /mnt/c/Users/User1/gnomad-browser/node_modules/sqlite3
node-pre-gyp ERR! node -v v15.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok

**Comment by nawatts** [comment]
The blog is hosted separately from the browser, so it will not appear in a development environment. In the production environment, a load balancer rule routes requests for `/blog*` to the blog server.

https://github.com/broadinstitute/gnomad-browser/blob/78274d30d4f96a66391601c2e9bf00651dc2f61e/deploy/manifests/ingress/gnomad.ingress.yaml#L24-L31

**Comment by GenomicsPrograms** [comment]
I previously tried creating a NewsPage.js with entries in NavBar.js and routes.js, but the localhost:/8008/news wouldn't render the content in NewsPage.js (I had copied the AboutPage.js and named its copy: NewsPage.js). What can I do to make my NewsPage.js render?

> 
> 
> The blog is hosted separately from the browser, so it will not appear in a development environment. In the production environment, a load balancer rule routes requests for `/blog*` to the blog server.
> 
> https://github.com/broadinstitute/gnomad-browser/blob/78274d30d4f96a66391601c2e9bf00651dc2f61e/deploy/manifests/ingress/gnomad.ingress.yaml#L24-L31

**Comment by nawatts** [comment]
That approach should work, though the new route will need to come before `<Route component={PageNotFoundPage} />`. This worked for me:

NewsPage.js
```js
import React from 'react'
import { PageHeading } from '@gnomad/ui'

import DocumentTitle from './DocumentTitle'
import InfoPage from './InfoPage'

export default () => (
  <InfoPage>
    <DocumentTitle title="News" />
    <PageHeading>News</PageHeading>
  </InfoPage>
)
```

routes.js
```js
import NewsPage from './NewsPage'
...
<Route exact path="/news" component={NewsPage} />
<Route component={PageNotFoundPage} />
...
```

**Comment by GenomicsPrograms** [comment]
What did the news entry look like in NavBar.js? 

I tried the following, but still get a "Something went wrong" message on the rendered /news page.

```
  <li>
             <a href="/news">News</a>
 </li>
```

and 
```
  <li>
             <Link>to="/news" onClick={this.closeMenu}>
               News
             </Link>
 </li>
```

> 
> 
> That approach should work, though the new route will need to come before `<Route component={PageNotFoundPage} />` (Switch will select the first route that matches the URL and `<Route component={PageNotFoundPage} />` matches any URL). This worked for me:
> 
> NewsPage.js
> 
> ```js
> import React from 'react'
> import { PageHeading } from '@gnomad/ui'
> 
> import DocumentTitle from './DocumentTitle'
> import InfoPage from './InfoPage'
> 
> export default () => (
>   <InfoPage>
>     <DocumentTitle title="News" />
>     <PageHeading>News</PageHeading>
>   </InfoPage>
> )
> ```
> 
> routes.js
> 
> ```js
> import NewsPage from './NewsPage'
> ...
> <Route exact path="/news" component={NewsPage} />
> <Route component={PageNotFoundPage} />
> ...
> ```

**Comment by nawatts** [comment]
Either should work, though using react-router's `Link` is probably preferable.

If you're seeing "Something went wrong", then there's a render error being caught by the [ErrorBoundary component in routes.js](https://github.com/broadinstitute/gnomad-browser/blob/78274d30d4f96a66391601c2e9bf00651dc2f61e/browser/src/routes.js#L68). Maybe something in the NewsPage component?
