### ISSUE TITLE
Configure Ingress to redirect to HTTPS

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#680]
It's now possible to configure an Ingress to redirect HTTP to HTTPS at the load balancer. This would simplify Nginx configuration.

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect

**Comment by sjahl** [comment]
![Screenshot_2021-02-19 Configuring Ingress features Kubernetes Engine Documentation.png](https://images.zenhubusercontent.com/5ffda9473cf73afe2fe00249/fdf9d4ea-1324-42cb-a352-a7550d7e801c)

Note that this requires a relatively recent GKE/k8s version (1.18+)

**Comment by nawatts** [comment]
The browser cluster is on the [stable release channel](https://cloud.google.com/kubernetes-engine/docs/release-notes-stable), so it might be a while before it's upgraded to 1.18.10-gke.600.
