### ISSUE TITLE
Update DECIPHER links to protein view page

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad-browser#688]

**Comment by nawatts** [comment]
Looks like DECIPHER has been updating their site and changing URLs.

We used to link to `https://decipher.sanger.ac.uk/gene/<gene id>#overview/protein-info`.

Yesterday, `https://decipher.sanger.ac.uk/gene/<gene id>/overview/protein-info` was working. Today, it's `https://decipher.sanger.ac.uk/gene/<gene id>/overview/protein-genomic-info`.
