### ISSUE TITLE
AC_male not equal to number of hemizygous in chromosome X or chromosome Y

### ISSUE THREAD

**Issue by amieeyun** [broadinstitute/gnomad-browser#709]
Hi， there are some variants ,which AC_male not equal to number of hemizygous in chromosome X or chromosome Y.
In variants vcf files ,there is only nhomalt but no hemizygous num,so I try to replace the hemizygous num with AC_male,but AC_male not equal to hemizygous num for asome variants.
eg:
hg19:X-200860-T-C,AC_male=97061,nhomalt_male=35265,but Number of hemizygotes=0
hg38:X-284195-G-C,AC_male=4,nhomalt_male=0,Number of hemizygotes=0

-------------- 👆 Click "Preview"!

Instead of filing an issue on GitHub, please email questions about the
gnomAD or ExAC datasets to [gnomad@broadinstitute.org](mailto:gnomad@broadinstitute.org).

Answers to frequently asked questions may be found at https://gnomad.broadinstitute.org/faq.

**Comment by nawatts** [comment]
Hi @amieeyun,

These variants show 0 hemizygotes because they are in pseudoautosomal regions.

![Screen Shot 2021-02-08 at 10 01 22 AM](https://user-images.githubusercontent.com/1156625/107237750-14b14d00-69f5-11eb-8316-875ef8541bbe.png)
