### ISSUE TITLE
Add FAQ "How many variants are in gnomAD?"

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#752]

**Comment by nawatts** [comment]
https://atgu.slack.com/archives/CNLMF0JLV/p1617284552055900

**Comment by KalinNonchev** [comment]
gnomAD WGS v3.1.1 - 759.302.267 variants
gnomAD WGS v2.1.1 - 261.942.336 variants

**Comment by nawatts** [comment]
Thanks @KalinNonchev.

We're also working on collecting a larger list of metrics (total number of loss-of-function variants, etc.) to include with this.

**Comment by sjahl** [comment]
I believe this is encoded on https://gnomad.broadinstitute.org/stats these days!
