### ISSUE TITLE
Create in-browser liftover functionality between v2.1 (GRCh37) and v3 (GRCh38) variants

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#754]
After much discussion amongst Council members, no single approach to an interim combined exome + genome GRCh38 liftover callset could be agreed upon.

Instead, the Council agreed that providing an in-browser liftover function to link v2.1 GRCh37 exome allele frequencies to corresponding variants in v3.1 (GRCh38) would work to tide us over until we finish v4 (native GRCh38 exomes + v3.1 genomes).

- Any variant that occurs in v2.1 that maps unambiguously to a corresponding GRCh38 will have a link that connects the two variants
- If a v2.1 variant does *not* happen to occur in v3.1 but can be lifted over to GRCh38 unambiguously, the link should redirect the user to a region around where the variant would occur if it happened to exist in v3.1
- If a v2.1 variant maps to multiple sites, display a disambiguation page with multiple sites for the user to choose, plus an informative error message
- Council only concerned about supporting variants +/- 50 bp around exons

The methods group will work with Nick to support whatever needs to be done computationally.

**Comment by nawatts** [comment]
> If a v2.1 variant maps to multiple sites, display a disambiguation page with multiple sites for the user to choose, plus an informative error message

Going from GRCh37 to GRCh38, is it possible to end up with a variants mapped to multiple sites? [hl.liftover](https://hail.is/docs/0.2/functions/genetics.html#hail.expr.functions.liftover) returns a single locus expression. I could see this happening if we mapped GRCh38 loci to GRCh37.

**Comment by gtiao** [comment]
Open questions: was the liftover callset created using hl.liftover(), or was it based on DSP's liftover? If the latter, does it show variants that map to multiple loci from GRCh37->GRCh38? If the former, how does Hail determine which locus to return?

Council PIs would prefer to lift over sites in v2.1 GRCh37 (including genomes) and not restrict to exons +/- 50 bp. How much additional storage space and compute would this take to facilitate?

**Comment by nawatts** [comment]
Storage space for the browser should be trivial. All v2 variant data is ~350 GB and this would be much less data per variant.

**Comment by gtiao** [comment]
Let's lift over all sites in v2.1 (exomes + genomes)

KC [reports](https://atgu.slack.com/archives/CRA2TKTV0/p1617743306009900) the liftover callset was created based on DSP's liftover. However, Nick has noted some problems with the `original_alleles` annotation while sanity checking the liftover callset. This needs to be addressed before we can move forward.

**Comment by gtiao** [comment]
Nick and I have corresponded with Jonn Smith, who is still at Broad and kept (thankfully for us) detailed records of what he did:

```
I saved everything I did in the gatk codebase in anticipation that I might have to do it again.  It's all located here:

https://github.com/broadinstitute/gatk/tree/master/scripts/funcotator/data_sources/gnomAD

Specifically, I ran liftoverVcf.wdl with liftoverVcf_Gnomad2.1_exome.json and liftoverVcf_Gnomad2.1_genome.json as inputs.
```

Nick notes there are versions of GATK that allow a `--WRITE_ORIGINAL_ALLELES` option to be passed, but this was not set for the original v2.1.1 liftover run.

We need to:
- Re-run v2.1.1 liftover using this flag to preserve original alleles
- Update the existing v2.1.1 release files (HT and VCF) to populate the `original_alleles` annotation with the correct values
