### ISSUE TITLE
Systemically download gene regions

### ISSUE THREAD

**Issue by Shicheng-Guo** [broadinstitute/gnomad-browser#757]
Hi gnomAD browser support team, 

Is there any way to Systemically download all the gene regions used in gnomAD platform? How gnomAD handle multiple transcripts for each gene? 

Thanks. 

Shicheng

![image](https://user-images.githubusercontent.com/6641283/114888011-e4ac6e80-9dd6-11eb-95f2-4509fdaf22ab.png)

**Comment by nawatts** [comment]
Hi @Shicheng-Guo,

Those regions are taken from the start and end fields of gene features in GENCODE GTF files ([GENCODE v35](https://www.gencodegenes.org/human/release_35.html) for gnomAD v3.1 and [GENCODE v19](https://www.gencodegenes.org/human/release_19.html) for gnomAD v2.1).
