### ISSUE TITLE
Support unicode dashes in search box (for example chr2:166863579–166864271)

### ISSUE THREAD

**Issue by bw2** [broadinstitute/gnomad-browser#758]
Other sites or docs sometimes have [unusual dashes](https://jkorpela.fi/dashes.html), and copy-pasting these into the search box results in confusing behavior where the browser can't parse a normal-looking interval string. 

I've found one way to handle these is with [Unicode char classes](https://github.com/broadinstitute/liftover/blob/main/index.html#L153-L160)

**Comment by nawatts** [comment]
Cool, did not know about Unicode character classes.

Also found this article describing the properties available to match on: https://javascript.info/regexp-unicode#unicode-properties-p
