### ISSUE TITLE
some annotation counts not available for some variants in gnomAD V3

### ISSUE THREAD

**Issue by chenwenan** [broadinstitute/gnomad-browser#761]
### What you did:

https://gnomad.broadinstitute.org/variant/21-10538680-G-C?dataset=gnomad_r3_controls_and_biobanks

### What happened:
something wrong showed up

The reason is that some annotated counts are missing for some variants. This can be checked by: 

bcftools query -f'%AN %AN_controls_and_biobanks\n' -rchr21:10538680 gnomad.genomes.v3.1.1.sites.chr21.vcf.bgz

The output:
152310 .

Does the missing counts mean they are 0? 

Thanks

**Comment by nawatts** [comment]
Hi @chenwenan,

Thanks for pointing this out. It looks like the browser was not correctly handling this case where the variant is not found in a subset. This should be fixed now.

**Comment by chenwenan** [comment]
Great, Thank you for fixing this. 
Just to confirm: if the annotation is missing, that means the count corresponding to that annotation is 0, right?

**Comment by nawatts** [comment]
If the `AN_controls_and_biobanks ` annotation is missing, the variant was not observed in samples in the controls and biobanks subset.

**Comment by chenwenan** [comment]
Got it. Thanks. I assume the same logic applies to other AC_* AN_* annotations, right?

**Comment by nawatts** [comment]
Correct.
