### ISSUE TITLE
Clarify that homo- and hemi-zygous genotypes are included in age distribution for chrX variants

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#785]
A user recently wrote in to report that the age histogram increased when the "Include homozygous variant carriers" toggle was clicked on for a variant on chrX, despite the fact that there are 0 homozygous counts in the AF table. These are likely due to hemizygous individuals counted as homozygous for the purposes of the distribution.

One solution would be to change the wording for the option on the age distribution display to "homo- or hemizygous" for chrX variants

**Comment by gtiao** [comment]
See email: https://atgu.slack.com/archives/CNL7NA6H2/p1625069910072400

**Comment by nawatts** [comment]
I'm assuming this applies to variants on the Y chromosome also?

**Comment by nawatts** [comment]
It does apply to variants on the Y chromosome. For example, https://gnomad.broadinstitute.org/variant/Y-2786926-C-T?dataset=gnomad_r3.
