### ISSUE TITLE
extracting only male data from gnomad 3.1. genomes

### ISSUE THREAD

**Issue by Kaskere** [broadinstitute/gnomad-browser#786]
Hi,

I try to use public gnomad genomes for downstream tests, but the problem is that I only need male controls from these files. The file looks like this (also header, but not shown due to large size)
I have to remove all parts of file that contains _XX in the end ( need to do test against men control, so all women data should be removed from control file)

I tried 
`
bcftools annotate -x '%INFO/AC_non_v2_XX\t%INFO/AN_non_v2_XX\t%INFO/AF_non_v2_XX\t%INFO/nhomalt_non_v2_XX\t%INFO/AC_non_cancer_fin_XX`
and
`bcftools filter -i 'INFO/controls_XY'`
but got Error: `no such tag defined in the VCF header`

Is there some way to remove female controls from this file without damaging file structure?

**Comment by nawatts** [comment]
Hi @Kaskere,

It looks like you're on the right track.

`bcftools annotate` can be used to remove all annotations related to XX subsets.

As for the filter, there is no INFO field named `controls_XY`. `AC_controls_and_biobanks_XY` may be what you are looking for. `bcftools filter -i 'INFO/AC_controls_and_biobanks_XY > 0'` works.
