### ISSUE TITLE
Unable to search gnomAD SVs v2.1 by variant id?

### ISSUE THREAD

**Issue by Jkmcameron** [broadinstitute/gnomad-browser#793]
![image](https://user-images.githubusercontent.com/14365419/128624454-287da906-3fb5-4fef-9e6e-b09b0296becb.png)
![image](https://user-images.githubusercontent.com/14365419/128624469-d18efd8c-2e0c-4721-b6ff-f43d6e13fd8b.png)
![image](https://user-images.githubusercontent.com/14365419/128624593-8f4bc5a9-bcf5-4a57-9ab6-c738999b7c77.png)

I can find the CNVs I'm looking for in gnomAD SVs v2.1 (thanks for that) but I can't reference them anywhere without providing a direct link because there is no option to search the gnomAD SVs v2.1 database as there is for the other databases. It would be nice to be able to use the provided variant ids to look a structural variant up by in the browser.

**Comment by Jkmcameron** [comment]
https://github.com/broadinstitute/gnomad-browser/pull/794

I seemingly fixed it, works in localhost in any case

![image](https://user-images.githubusercontent.com/14365419/128671759-44709974-a801-4a2f-8a72-82d313aa0a15.png)

**Comment by nawatts** [comment]
Resolved by #794.
