### ISSUE TITLE
LitVar Integration

### ISSUE THREAD

**Issue by Jkmcameron** [broadinstitute/gnomad-browser#795]
LitVar automatically skims PubMed for any literature citing a specific variant. It recognizes multiple different formats for variants (rs121913527, A146T, and c.436G>A all being recognized as the same variant) and searches the literature accordingly.

Below you can see its use on dbSNP:
![image](https://user-images.githubusercontent.com/14365419/128702067-3349673a-2608-4d39-86c2-e9ff4d69a823.png)
![image](https://user-images.githubusercontent.com/14365419/128702559-8e73d69a-f302-41c6-b67b-dd3817d296c5.png)

**Comment by nawatts** [comment]
No plans to implement this at this time. LitVar is easily reachable from dbSNP, which is already linked to from variant pages.

This would also be limited to linking based on rsID, which we would prefer to avoid. rsIDs are ambiguous and we don't keep rsIDs in the browser up to date with changes in dbSNP.
