### ISSUE TITLE
gnomad.v3.1.1.lof_metrics.by_gene.txt.bgz 

### ISSUE THREAD

**Issue by Shicheng-Guo** [broadinstitute/gnomad-browser#819]
Dear gnomAD support:

Do we have gnomad.v3.1.1.lof_metrics.by_gene.txt.bgz available to download?  I know gnomad.v2.1.1.lof_metrics.by_gene.txt.bgz is available. 

Thanks 

Shicheng

**Comment by nawatts** [comment]
No, gene constraint has not been calculated for gnomAD v3.
