### ISSUE TITLE
'public requester pays' restriction on gnomAD v3.1.2 HGDP + 1KG callset downloads

### ISSUE THREAD

**Issue by ymavura3** [broadinstitute/gnomad-browser#829]
### Restrictions on v3.1.2 HGDP + 1KG downloads:

Hello gnomAD team,
Thank you for the work you've done for the release of gnomAD v3.1.2 for download on Oct 22 2021, I appreciate it.
I unsuccessfully attempted to download the 1KG + HGDP set from Google Cloud, but it seems that it is set to 'public requester pays'. 
(gs://gnomad-public-requester-pays/release/3.1.2/vcf/genomes/gnomad.genomes.v3.1.2.hgdp_tgp.chrY.vcf.bgz)

I wanted to confirm with you if whether we are indeed supposed to provide a project number to download v3.1.2. If a project number is not needed, I am kindly requesting for the 'public requester pays' setting to be disabled for us to successfully download the data.
Thanks.

<!--

Any of the following information will be helpful:

* Screenshots
   How to take a screenshot on macOS: https://support.apple.com/en-us/HT201361
   How to attach an image to an issue: https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

* Error messages that appear on the page or in the browser console
   How to open the console on Chrome: https://developers.google.com/web/tools/chrome-devtools/console/#opening_the_console

--

[>]

**Comment by nawatts** [comment]
gnomAD v3.1.2 is now available through Google Cloud Public Datasets. Links on the [downloads page](https://gnomad.broadinstitute.org/downloads) have been updated.

`gsutil ls gs://gcp-public-data--gnomad/release/3.1.2/`

**Comment by kalon33** [comment]
@nawatts thanks a lot!
