### ISSUE TITLE
Use Terraform to manage cloud infrastructure

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#840]
Currently, cloud infrastructure for the browser is managed using gcloud or the Cloud Console and changes manually added to a Python script that sets up everything from scratch ([deploy/deployctl/subcommands/setup.py](https://github.com/broadinstitute/gnomad-browser/blob/efcee6869093bd45a10309e522d80498e88f277e/deploy/deployctl/subcommands/setup.py)).

Instead, infrastructure should be managed using Terraform.

**Comment by sjahl** [comment]
Prod is now managed with terraform, using pull request `plan`/`apply` automation via Atlantis. Follow-up PR to come for removing the setup.py subcommand. Gonna leave the command in there for now, until we get consumable documentation out for helping others use our terraform modules.
