### ISSUE TITLE
Handle requests for gnomAD versions that are no longer available

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#844]
When a specific version/subset is included, the URL includes the gnomAD version. For example:

- v2 https://gnomad.broadinstitute.org/variant/1-55516888-G-GA?dataset=gnomad_r2_1
- v3 https://gnomad.broadinstitute.org/variant/1-55051215-G-GA?dataset=gnomad_r3

Once gnomAD v4 is released, v3 will no longer be available in the browser. We still want to support requests for v3 so that existing links are not broken. We could either automatically redirect to the latest gnomAD version (for the same reference genome as the requested version) or display a message stating that the requested version is no longer available and link to the latest version, so that it is clear that the data has changed from the page that was linked to.

**Comment by mattsolo1** [comment]
Closed by #1178. For now all legacy datasets are still available.
