### ISSUE TITLE
Create data pipeline for v4 variants

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#849]
Create a [data pipeline](https://github.com/broadinstitute/gnomad-browser/tree/main/data-pipeline/src/data_pipeline) for gnomAD v4 variants.

Much of the [v3 pipeline](https://github.com/broadinstitute/gnomad-browser/blob/main/data-pipeline/src/data_pipeline/datasets/gnomad_v3/gnomad_v3_variants.py) can probably be reused, but exome data will need to be added and joined to genome data.

**Comment by rileyhgrant** [comment]
Close by #1178
