### ISSUE TITLE
Implement GraphQL queries for v4 variants

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#850]
Add v4 as an option for dataset arguments.
- [graphql-api/src/graphql/types/dataset-id.graphql](https://github.com/broadinstitute/gnomad-browser/blob/main/graphql-api/src/graphql/types/dataset-id.graphql)
- [graphql-api/src/datasets.js](https://github.com/broadinstitute/gnomad-browser/blob/main/graphql-api/src/datasets.js)

Add GraphQL queries for v4 variants.
- [graphql-api/src/queries/variant-datasets](https://github.com/broadinstitute/gnomad-browser/tree/main/graphql-api/src/queries/variant-datasets)
- [graphql-api/src/queries/variant-queries.js](https://github.com/broadinstitute/gnomad-browser/blob/main/graphql-api/src/queries/variant-queries.js)

**Comment by rileyhgrant** [comment]
Closed by #1178
