### ISSUE TITLE
Update version of VEP used in ClinVar data pipeline

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#851]
When starting a Dataproc cluster for the GRCh38 ClinVar data pipeline ([deploy/docs/UpdateClinvarVariants.md](https://github.com/broadinstitute/gnomad-browser/blob/main/deploy/docs/UpdateClinvarVariants.md)), use the same VEP init script and configuration as used to annotate v4.

**Comment by mattsolo1** [comment]
See line https://github.com/broadinstitute/gnomad-browser/blame/0d3d811402e45c946ce913b70ccdca3b102aaad4/deploy/docs/UpdateClinvarVariants.md#L27=
