### ISSUE TITLE
Update components that render conditional on dataset (part 1)

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#853]
Many components render differently based on the current dataset. Check for conditionals such as `datasetId.startsWith('gnomad_r3')`.

Ideally, instead of checking the dataset ID directly, abstract checks into functions in [dataset-metadata](https://github.com/broadinstitute/gnomad-browser/tree/main/dataset-metadata). For example, `datasetHasGenomes` vs `datasetId !== 'exac'`.

**Comment by phildarnowsky-broad** [comment]
I still have quite a few instances of this to change, but for strategic reasons I decided to release the first batch of changes while continuing to work on them--see https://github.com/broadinstitute/gnomad-browser/pull/980 for details.
