### ISSUE TITLE
Add v4 read data

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#857]
See instructions in [reads/README.md](https://github.com/broadinstitute/gnomad-browser/tree/main/reads#adding-reads-for-a-dataset).

Since v4 will use a different version of VEP than v3, the transcripts track in the IGV.js viewer will also need to be updated.
- [reads/README.md#reference-data](https://github.com/broadinstitute/gnomad-browser/tree/main/reads#reference-data)
- [browser/src/ReadData/ReadData.js](https://github.com/broadinstitute/gnomad-browser/blob/b4e38686e23fe4a31ff7c9541fe78b82b4df286b/browser/src/ReadData/ReadData.js#L293-L301)

**Comment by rileyhgrant** [comment]
Closed by #1178
