### ISSUE TITLE
Update version of GENCODE used in genes data pipeline

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#858]
Update the version of GENCODE used in the genes data pipeline to match the version used in the version of VEP used to annotate v4.

https://github.com/broadinstitute/gnomad-browser/blob/b4e38686e23fe4a31ff7c9541fe78b82b4df286b/data-pipeline/src/data_pipeline/pipelines/genes.py#L36-L38

**Comment by rileyhgrant** [comment]
Per [this slack thread](https://the-tgg.slack.com/archives/C018PB68VU5/p1677689628398959?thread_ts=1676408384.152109&cid=C018PB68VU5), the next GTEx release is going to be on Gencode 39.

**Comment by rileyhgrant** [comment]
Closed by #1222
