### ISSUE TITLE
Update MANE Select transcripts

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#859]
Check if a newer version of [MANE Select](https://www.ncbi.nlm.nih.gov/refseq/MANE/) transcripts are available and if so, update the version used in the genes data pipeline.

https://github.com/broadinstitute/gnomad-browser/blob/b4e38686e23fe4a31ff7c9541fe78b82b4df286b/data-pipeline/src/data_pipeline/pipelines/genes.py#L82-L84

**Comment by mattsolo1** [comment]
See Qin He's comment: https://the-tgg.slack.com/archives/C018PB68VU5/p1691766412223619

**Comment by KoalaQin** [comment]
Yeah, the discussion was long, in brief, I think you can use v0.95 as you have now, the version integrated in VEP 105 for gnomAD v4, I guess you filter by `MANE_status` to get only the **18584** `MANE Select` transcripts in your pipeline.

**Comment by mattsolo1** [comment]
I went to modify the pipeline code & it seems we already filter this way: https://github.com/broadinstitute/gnomad-browser/blob/c10bc15ca9dc18fd1c4aa953694c731df9000ecc/data-pipeline/src/data_pipeline/data_types/mane_select_transcript.py#L14

**Comment by KoalaQin** [comment]
Closing as we decided on the version for v4 and the pipeline.
