### ISSUE TITLE
Extend variants schema with new fields added in v4

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#861]
If v4 adds new fields to variant data (such as a combined FAF for exomes/genomes), extend the [variant GraphQL schema](https://github.com/broadinstitute/gnomad-browser/blob/main/graphql-api/src/graphql/types/variant.graphql) to include them. Ensure that these fields are compatible with older datasets shown in the browser (make them nullable).

**Comment by rileyhgrant** [comment]
Closed by #1178
