### ISSUE TITLE
Update liftover

### ISSUE THREAD

**Issue by nawatts** [broadinstitute/gnomad-browser#876]
Currently, lifted over v2 variants are annotated based on their presence in gnomAD v3.

https://github.com/broadinstitute/gnomad-browser/blob/248432d6b9658938eba6bc25638820f07327db1e/data-pipeline/src/data_pipeline/pipelines/liftover.py#L53-L60

That needs to be updated to use gnomAD v4.

**Comment by mattsolo1** [comment]
Closed via #1178
