### ISSUE TITLE
Add published gnomAD mito paper to browser "Publications" page

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#877]
Paper has been accepted in principle and we are waiting on proofs and a publication date!

**Comment by phildarnowsky-broad** [comment]
@mattsolo1 Should the DOI be updated as well? The DOI for the published version appears to be 10.1101/gr.276013.121

**Comment by mattsolo1** [comment]
Oops yeah definitely use that DOI for the published version
