### ISSUE TITLE
Update links to GCP and Azure for STR downloads on browser

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#881]
For Friday's release, we displayed only AWS links as we had control over the timing of the data sync to AWS. The files should now all be synced to GCP and Azure and available to the public on those platforms.

**Comment by mattsolo1** [comment]
See: https://gnomad.broadinstitute.org/downloads#v3-short-tandem-repeats

Notice how the STR datasets only have the Amazon link. Need to add GCP/Azure links, similar to the other datasets on the page.

![image](https://user-images.githubusercontent.com/8867295/172675172-37629fe7-42a6-4690-a1f4-4826d149741b.png)
