### ISSUE TITLE
Add GCP public links for v3.1.3 STR release on Downloads page

### ISSUE THREAD

**Issue by gtiao** [broadinstitute/gnomad-browser#886]
Currently, only the Amazon links are listed, despite the fact that the data are available on GCP

**Comment by mattsolo1** [comment]
I think we've resolved this with https://github.com/broadinstitute/gnomad-browser/pull/905

@bw2 everything look OK?

**Comment by bw2** [comment]
Yes, all 3 links work under https://gnomad.broadinstitute.org/downloads#v3-short-tandem-repeats

<img width="890" alt="image" src="https://user-images.githubusercontent.com/6240170/175356273-1e6e4fb7-b40c-486b-b172-c47830ad1f09.png">

The files are really small (< 1Gb), so I think it's fine that they're only hosted on Amazon.
