### ISSUE TITLE
Populations included/excluded in the Popmax Filtering AF calculation

### ISSUE THREAD

**Issue by rcastelo** [broadinstitute/gnomad-browser#893]
Hi, for the following variant:

https://gnomad.broadinstitute.org/variant/X-154534510-G-A?dataset=gnomad_r3

the gnomAD browser gives the value 0.0003709 in the "Popmax Filtering AF calculation". When hovering over it, it says "Latino/Admixed American", however, the maximum AF among populations is 0.004515 from Ashkenazi Jewish. The help popup for this calculation says "this is the highest disease-specific maximum credible population AF for which the observed AC is not compatible with pathogenicity", but since the difference is of an order of magnitude, I would like to ask if it is the case that Ashkenazi Jewish is excluded from this calculation. The current documentation of the gnomAD website doesn't seem to say anything about excluding populations to calculate AF_popmax. However, [GATK](https://gatk.broadinstitute.org/hc/en-us/articles/360035889931-Funcotator-Information-and-Tutorial) and the UCSC Genome Browser schemas for [v2](https://www.genome.ucsc.edu/cgi-bin/hgTables?db=hg19&hgta_group=varRep&hgta_track=gnomadExomes&hgta_table=gnomadExomes&hgta_doSchema=describe%20table%20schema) and [v3](https://genome.ucsc.edu/cgi-bin/hgTables?db=hg38&hgta_group=varRep&hgta_track=gnomadGenomesVariantsV3_1&hgta_table=gnomadGenomesVariantsV3_1&hgta_doSchema=describe%20table%20schema) do say that Ashkenazi, Finnish, and indeterminate ancestry populations are excluded.

Could you confirm whether there are populations excluded in the calculations of AF_popmax for the latest version 3.1.2 of the gnomAD data and, in such a case, which are these excluded populations?

Thanks!

robert.

**Comment by ch-kr** [comment]
Hi Robert,

Thank you for reaching out. The popmax calculation for gnomAD v2 excludes Ashkenazi Jewish (asj), European Finnish (fin), and indeterminate/"Other" (oth) populations. The popmax calculation for gnomAD v3 also excludes Amish (ami) and Middle Eastern (mid) populations in addition to these three populations (asj, fin, oth). 

We will work on adding this information to the browser help pages so that this is more clear in the future.

Regards,
Katherine

**Comment by rcastelo** [comment]
Great, thanks for clarifying!
