### ISSUE TITLE
Update ClinVar

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/gnomad-browser#925]
Clinical users find it useful to have the most recent version of ClinVar in the gnomAD browser. Therefore ClinVar data must be routinely downloaded, parsed, and loaded. Instructions are [here](https://github.com/broadinstitute/gnomad-browser/blob/main/deploy/docs/UpdateClinvarVariants.md). This should probably happen at a monthly frequency (?).

**Comment by anneodonnell** [comment]
Monthly is ideal but if that's too much to ask for, then quarterly would be reasonable.

**Comment by rileyhgrant** [comment]
Related: #984

**Comment by rileyhgrant** [comment]
Updating of ClinVar variants pipeline is fixed thanks to help from the methods team on the VEP troubles.

Leaving this issue open until relevant changes in the code is merged, but the ClinVar variants are now referring to a September 2022 release. I will put in on my schedule to update this at least Quarterly, if not Monthly.

**Comment by rileyhgrant** [comment]
> Monthly is ideal but if that's too much to ask for, then quarterly would be reasonable.

Relevant changes are now merged, I will put in on my schedule to update this at least Quarterly, if not Monthly.
