### ISSUE TITLE
2 rare variants table on gene page

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad-browser#956]
### What you did:
Building off of Laurent's statistical phasing work, Sarah Stenton, Julia, and Kaitlin have been working on the two rare variant calculations (with different allele frequencies and variant types included). I'm envisioning this as a table that would be in the place of the constraint table - on a tab where you can toggle between the constraint or 2 rare variant data. 

I've asked Sarah to start thinking about what data would be the most helpful to show (as the download version will likely have more subcategories than we will show on the browser). The data isn't quite ready yet so I'm just adding a ticket to have this on the development road map. 

This is lower priority than gnomAD v4 but there is a chance it will be ready before v4 so if there is extra bandwidth, it's something to potentially start thinking about while waiting for the v4 data.

**Comment by mattsolo1** [comment]
We'll add this to the roadmap -- thanks Anne

**Comment by slstenton** [comment]
The two rare variant data is ready now and I have a mock-up of the browser display. We've added it to the agenda of the next  gnomAD browser roadmapping meeting.

**Comment by phildarnowsky-broad** [comment]
- [ ] Active table toggle
- [ ] Data into dual-rare table
- [ ] Dual-rare table collapse/expand toggle
- [ ] Tooltips

**Comment by slstenton** [comment]
We're making some updates to the table to also count homozygous variant carriers -- this won't change the table structure but will change the counts in the cells. I hope we will have it ready in the coming week or two. We'd also like to move "missense + missense" from the expanded table to the main table view.

**Comment by phildarnowsky-broad** [comment]
For transparency, I am stalled on this and have been for roughly two days now, because as periodically happens, an important part of my dev environment has stopped working for no obvious reason.

**Comment by phildarnowsky-broad** [comment]
@slstenton I'll soon be ready to work with the data but I don't seem to have access to the storage bucket in question.

**Comment by slstenton** [comment]
@phildarnowsky-broad the data are in two places:

gs://gnomad-sarah/compound_hets/chet_per_gene.tsv.gz
gs://gnomad/projects/compound_hets/exomes_chet_per_gene_0.05_3_prime_UTR_variant_vp.tsv.gz

Do you have access to either of these?

As an update from our side: We're currently re-thinking which numbers we'd like to display in the browser, and I'm also still working on adding in counts of homozygous variant carriers.

**Comment by phildarnowsky-broad** [comment]
@slstenton no, no luck with either of those URLs, I think @sjahl might be the person to ask about this (sorry if I got that wrong Steve).

For now then I'll populate the table with dummy data, and also I'll make sure to leave us a clear path to change the figures we show if we want.

**Comment by sjahl** [comment]
@phildarnowsky-broad Let me check that we don't have to do any paperwork for gnomad data access first, and then I can get you read access.

**Comment by sjahl** [comment]
@phildarnowsky-broad I've added the browser team members to the gnomad read access group. Try again?

**Comment by phildarnowsky-broad** [comment]
@sjahl /cc @slstenton thanks I have access now

**Comment by phildarnowsky-broad** [comment]
@sjahl @slstenton that is, I was able to download `chet_per_gene.tsv.gz`, but `exomes_chet_per_gene_0.05_3_prime_UTR_variant_vp.tsv.gz` is in a requester-pays bucket. Would these files be the same data, or will I need to take both and combine them?

**Comment by slstenton** [comment]
@phildarnowsky-broad the data is exactly the same.

**Comment by phildarnowsky-broad** [comment]
@slstenton excellent, we're good on that then.

After talking with the team a little, I changed my mind and I think it'd be best to build out the backend portions of this now as well, on the assumption that though there might be changes in the data you want to display or how you calculate it, the final choices will look more like what's in the mockup than not. The only question is, do you think that's a safe assumption?

**Comment by slstenton** [comment]
The changes we're discussing will likely involve:
1) the consequence categories displayed in the "main" display table
2) the number of different values displayed in the cells (we may add additional numbers e.g., homozygous counts in addition to the "in trans" counts, but we're still discussing what is best as we don't want the table to become too busy)

**Comment by phildarnowsky-broad** [comment]
@slstenton OK sounds good. I have two more questions at the moment about the data:

1. How do the columns `n_chet`, `n_same_hap`, `n_unphased`, and `n_het_het` map to the two counts in each table cell?
2. Spot checking, it looks like it may be that `population` is always `all`. Is this so? If it's not so, how does `population` enter into the calculation?

**Comment by slstenton** [comment]
The first number in front of the brackets should be "n_het_het" and within the brackets should be "n_chet". All others can be ignored. Population is always "all" in this analysis, so that can also be ignored.

**Comment by phildarnowsky-broad** [comment]
@slstenton One more question, does the data here cover all genes in gnomAD or only a subset?

**Comment by slstenton** [comment]
It runs on all genes, the only reason a gene would be missing is if there were no individuals with two rare variants counted in that gene, in which case the table should be populated with zeros.

**Comment by phildarnowsky-broad** [comment]
Brief update before I go on winter break: this is ready for code review apart from needing the tooltips and some assorted frontend styling fixes done. Also, the data pipeline in its current shape should work end-to-end, but I haven't yet tried it due to the amount of time it takes to run in full.

**Comment by phildarnowsky-broad** [comment]
@slstenton This is now in code review. I'm working on getting a demo instance set up that you can QA on, but in the meantime, here are some screenshots from my development machine.



![Image](https://user-images.githubusercontent.com/107062965/211601232-e2377404-d66c-4e1a-bbcd-861abed85f6a.png)
![Image](https://user-images.githubusercontent.com/107062965/211601231-36ca369d-a798-42ba-be0f-449efbf1ba63.png)

**Comment by phildarnowsky-broad** [comment]
@slstenton sounds good, I will keep an eye out for those tables.

**Comment by phildarnowsky-broad** [comment]
@slstenton one small point regarding the tooltips, I'm told that if we leave off the "v1" from the end of the biorxiv URL, it'll automatically link to the newest version of the given paper, in case there are revised versions in the future. I'm guessing that's desirable, but if it's important that these link to a specific version of the paper rather than whatever the latest might be, please let me know.

**Comment by slstenton** [comment]
@phildarnowsky-broad that's great to know about biorxiv, I think it would be great to always link to the most recent version.

Here are the paths to the updated results tables:

For the two heterozygous rare variant counts:
gs://gnomad-sarah/compound_hets/chet_unphased_same_hap_per_gene.tsv

For the homozygous rare variant counts:
gs://gnomad-sarah/compound_hets/het_hom_per_gene.tsv

We also introduced the "priority counting" discussed in the last meeting so that on the hover over box, we can also display values for unphased and in cis (whereby in trans + unphased + in cis always equal to the count for two het variants):
two het variants: ('n_any_het_het')
in trans ('n_chet')
unphased ('n_unphased_without_chet')
in cis ('n_same_hap_without_chet_or_unphased')

I've also attached the updated powerpoint from our last meeting.

[two_rare_variants_gnomad_browser.pptx](https://github.com/broadinstitute/gnomad-browser/files/10404886/two_rare_variants_gnomad_browser.pptx)

**Comment by phildarnowsky-broad** [comment]
@slstenton I'm looking at the new data and new PPT and here are the differences I observe, please let me know if you see anything important I've overlooked:

- The set of consequences in the un-expanded version of the table is generally different
- The set of consequences in the expanded version are the same except that we add supporting/supporting at the point shown
- Each cell of the table shows the two-het count, with the trans count in parens
- Each cell of the table gets a tooltip now, showing all four counts
- Bioarxiv links to have the versions removed so they always point to latest version
- New caption over the existing tables
- New homozygous table
- Disclaimers somewhere TBD (see below)

And here are a few questions that I have:

- I don't see an expanded version of the homozygous table. I'm thinking if the user expands the heterozygous table, the homozygous table should remain as-is. An alternative might be to have the homozygous table disappear if the heterozygous table is expanded, to free up some room for the expanded heterozygous table. Please let me know if you have a preference, or if there is supposed in fact to be an expanded homozygous table as well.
- For these disclaimers: I'm thinking the best approach might be to join them together into a single text, and have that be the tooltip for the caption for the heterozygous table. Does that sound good to you?

**Comment by slstenton** [comment]
@phildarnowsky-broad it all looks correct, thank you.

There doesn't need to be an expanded homozygous table. We think it's best for the homozygous table to disappear when the heterozygous table is expanded.

For the disclaimers, it sounds good to combine them, and to add them as a tooltip. In which case, can we write:

Variant phase for two rare heterozygous variants is based on prediction (add link to preprint). In very rare cases an individual will be counted in the homozygous table and in the two heterozygous rare variant table if they carry a rare homozygous variant in addition to a rare pair of heterozygous variants in the same gene.

**Comment by slstenton** [comment]
@phildarnowsky-broad could we also add links to the variant co-occurrence blog post (https://gnomad.broadinstitute.org/news/2021-07-variant-co-occurrence-phasing-information-in-gnomad/) and the upcoming two rare variant feature blog post.

**Comment by phildarnowsky-broad** [comment]
@slstenton sure we can add those links as well.

One problem I've just noticed however, is that with these links in a tooltip, it's not really practical to click them or even copy/paste. What if, instead, we do like we do with the background information for the constraint table: add a "?" icon that links to all the needed text in a help modal? I've attached screenshots to show the elements I mean.



![Image](https://user-images.githubusercontent.com/107062965/213270554-c3bbd57e-ab89-4263-a9a3-5e9a119e6648.png)



![Image](https://user-images.githubusercontent.com/107062965/213270581-d13d54c6-7a8d-406a-a860-e058fc6ac945.png)

**Comment by phildarnowsky-broad** [comment]
Brief update here since it's been a while. I knocked out most of the small frontend changes rapidly, then got stuck for a few days on a tricky problem to do with the data pipeline. With some help from @mattsolo1 that looks to be resolved, and the last significant piece then is the new homozygous table.

**Comment by phildarnowsky-broad** [comment]
Reopened for code review earlier today.

**Comment by slstenton** [comment]
Notes from today:
- Add “predicted” or “estimated” when writing “number in trans”
- Change “LoF” to “pLoF”
- Consider changing “strong/moderate/supporting” to “strong/moderate/weak” OR list REVEL scores for the missense variants (e.g. REVEL ≥0.773) — but there were some concerns with this as pLoF should always be included

**Comment by phildarnowsky-broad** [comment]
also pad homozygous table to match width of heterozygous

**Comment by phildarnowsky-broad** [comment]
@slstenton re tooltips for consequence categories: do you want those on the homozygous table too? I can adapt the language for the heterozygous table if so, no need to write new ones.

**Comment by slstenton** [comment]
Good point, yes please. Could we also add the sentence "These data are from gnomAD v2 exomes only (n=125,748)." to the end of the (?) hover over.

**Comment by phildarnowsky-broad** [comment]
@slstenton a suggestion from @mattsolo1 regarding the help content: "I think we need to start with a high level description of what this feature is for. Currently the help tool jumps right into technical details without explaining how to use these tables."

**Comment by slstenton** [comment]
@phildarnowsky-broad yes, completely agree. We have drafted a blog post to explain the feature and it's uses, but a brief description here might also be useful. @ksamocha would you agree? or shall we add a link in the (?) hover over to the blog post?

**Comment by ksamocha** [comment]
I agree. It is a good suggestion to have a short, but general, introduction to what this is and how it works. You may be able to adapt this quickly from the blog post draft you already have, Sarah. After a few sentences (2-3), we can then list "For more information, see our blog post on the same topic" with a link out.

**Comment by phildarnowsky-broad** [comment]
@slstenton FYI I am planning to set up a demo incorporating the latest changes sometime on Monday. If you have the aforementioned introduction ready by then, I can include it. If not, it's simple to add it afterwards as well.

**Comment by slstenton** [comment]
@phildarnowsky-broad here's my suggestion:

Our variant co-occurrence tables tabulate the number of individuals with two rare variants co-occurring in the same gene by functional consequence and allele frequency. This feature builds off our variant co-occurrence (inferred phasing) work (see “[Variant Co-Occurrence (Phasing) Information in gnomAD](https://gnomad.broadinstitute.org/news/2021-07-variant-co-occurrence-phasing-information-in-gnomad/)”) and displays the count of individuals by predicted variant phase. By providing background frequencies of rare predicted damaging variant co-occurrence, our resource can be used to assess the probability that an observation of this kind, detected in a patient’s sample, may have occurred by chance. For more information, see our blog post [add link] on the same topic.

**Comment by phildarnowsky-broad** [comment]
@slstenton sounds good, do we have a URL for the blog post yet? If not I'll put in a link to the main page of the blog as a placeholder.

**Comment by slstenton** [comment]
@phildarnowsky-broad Thank you! We have a draft here, but it still needs some screenshots and examples adding to be finalized (https://docs.google.com/document/d/1mZOhdoafywC5ch18uOBkrUpsceT_fpOF/edit).

**Comment by slstenton** [comment]
The data tables for the downloads page are ready here:

**Comment by slstenton** [comment]
@phildarnowsky-broad two out of thee of the public links for the download page are ready (below) and the Azure link should be ready tomorrow:
GCP: gs://gcp-public-data--gnomad/release/2.1.1/secondary_analyses/variant_cooccurrence/
AWS: s3://gnomad-public-us-east-1/release/2.1.1/secondary_analyses/variant_cooccurrence/
Can we please add these to the gnomAD downloads page?
