### ISSUE TITLE
Link on publications page for Chen et al. no longer working

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/gnomad-browser#959]
### What you did:
Link on the publications page to Chen et al manuscript is no longer working
Chen, S., Francioli, L. C., Goodrich, J. K., Collins, R. L., Wang, Q., Alföldi, J., Watts, N. A., Vittal, C., Gauthier, L. D., Poterba, T., Wilson, M. W., Tarasova, Y., Phu, W., Yohannes, M. T., Koenig, Z., Farjoun, Y., Banks, E., Donnelly, S., Gabriel, S., Gupta, N., Ferriera, S., Tolonen, C., Novod, S., Bergelson, L., Roazen, D., Ruano-Rubio, V., Covarrubias, M., Llanwarne, C., Petrillo, N., Wade, G., Jeandet, T., Munshi, R., Tibbetts, K., gnomAD Project Consortium, O’Donnell-Luria, A., Solomonson, M., Seed, C., Martin, A. R., Talkowski, M. E., Rehm, H. L., Daly, M. J., Tiao, G., Neale, B. M., MacArthur, D. G. & Karczewski, K. J. A genome-wide mutational constraint map quantified from variation in 76,156 human genomes. bioRxiv 2022.03.20.485034 (2022). https://doi.org/10.1101/2022.03.20.485034

### What you expected to see after you did that:
Should link to the manuscript but it goes to a manuscript not found page. 

### What you actually saw after you did that:
I was able to find the manuscript here: https://www.biorxiv.org/content/10.1101/2022.03.20.485034v1

-->

**Comment by mattsolo1** [comment]
Looks like this resolved on its own... the link now works.
