### ISSUE TITLE
Age distribution FAQ question does not display Histograms

### ISSUE THREAD

**Issue by rileyhgrant** [broadinstitute/gnomad-browser#969]
### What you did:
Navigate to the question `What is the age distribution of in gnomAD` on the `help` page.

This bug currently happens on the live production gnomAD browser, in addition to in the current state of the `main` branch.

### What you expected to see after you did that:
Based on the relevant imported file, there should be a histogram that uses the gnomAD metadata to display the age distribution for different versions.

### What you actually saw after you did that:
The headers and paragraphs load, and there is a wrapper and svg element, but the element itself is blank.

* Screenshot
![age_distribution](https://user-images.githubusercontent.com/59549713/183766338-69abab6e-a394-46f3-97cd-3ec8e29bdb4d.jpg)

**Comment by rileyhgrant** [comment]
Will look at this more tomorrow, currently trying to trace when this happened to see what might have caused the issue.

The history of the [faq question](https://github.com/broadinstitute/gnomad-browser/commits/babd364256df5093b5ca7b05b9056a29eeb785ea/browser/help/faq/technical-details/what-is-the-age-distribution-in-gnomad.js?browsing_rename_history=true&new_path=browser/help/faq/technical-details/what-is-the-age-distribution-in-gnomad.tsx&original_branch=main) itself has not been touched for a while, nor has the [Histogram Component](https://github.com/broadinstitute/gnomad-browser/commits/babd364256df5093b5ca7b05b9056a29eeb785ea/browser/src/Histogram.js?browsing_rename_history=true&new_path=browser/src/Histogram.tsx&original_branch=main). This bug is currently in production, so it does not seem to be a related to the `ts-migrate` branch.

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant 
> This bug is currently in production, so it does not seem to be related to the ts-migrate branch, as production does not have this PR merged.

Yup--you anticipated my first question. :)

**Comment by phildarnowsky-broad** [comment]
FYI right now I am using `git bisect` to try and pinpoint the problem. There's still a bit to go, but so far I can tell that this has been broken since at least June 7, 2021--that's more than 14 months. Another example of the value of tests.

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant For your information, courtesy of `git bisect`. Hope this helps, please let me know if you want more help with this.

```
1d1eec15fae944c8daf272a26cb2b688417535bb is the first bad commit
commit 1d1eec15fae944c8daf272a26cb2b688417535bb
Author: Nick Watts <nwatts@broadinstitute.org>
Date:   Tue Mar 9 17:25:26 2021 -0500

    Combine help and FAQ

    Resolves #712

 browser/build.sh                          |   1 -
 browser/build/buildFAQ.js                 | 118 ---------------
 browser/build/buildHelp.js                |  92 +++++++++---
 browser/help/faq/faqTableOfContents.json  |  83 -----------
 browser/help/helpPageTableOfContents.json |  97 +++++++++++++
 browser/src/App.js                        |  24 ++--
 browser/src/EventEmitter.js               |  31 ----
 browser/src/MarkdownContent.js            |   2 +
 browser/src/NavBar.js                     |   4 +-
 browser/src/help/.gitignore               |   1 -
 browser/src/help/HelpButton.js            |  51 -------
 browser/src/help/HelpModal.js             | 225 -----------------------------
 browser/src/help/HelpPage.js              | 231 ++++++++++++++++++++++++++++++
 browser/src/help/HelpTopicModal.js        |  47 ++++++
 browser/src/help/HelpTopicPage.js         |  11 +-
 browser/src/help/InfoButton.js            |  44 +++---
 browser/src/help/faqStyles.js             |  15 --
 browser/src/help/helpState.js             |  23 ---
 browser/src/help/slugify.js               |  10 ++
 browser/src/help/toc.json                 |  28 ----
 browser/start.sh                          |   1 -
 21 files changed, 513 insertions(+), 626 deletions(-)
 delete mode 100755 browser/build/buildFAQ.js
 delete mode 100644 browser/help/faq/faqTableOfContents.json
 create mode 100644 browser/help/helpPageTableOfContents.json
 delete mode 100644 browser/src/EventEmitter.js
 delete mode 100644 browser/src/help/HelpButton.js
 delete mode 100644 browser/src/help/HelpModal.js
 create mode 100644 browser/src/help/HelpPage.js
 create mode 100644 browser/src/help/HelpTopicModal.js
 delete mode 100644 browser/src/help/faqStyles.js
 delete mode 100644 browser/src/help/helpState.js
 create mode 100644 browser/src/help/slugify.js
 delete mode 100644 browser/src/help/toc.json
```

**Comment by rileyhgrant** [comment]
Oohooo, nice!

I'll have to read more up on `git bisect`. Thanks for doing that sleuthing!

**Comment by phildarnowsky-broad** [comment]
@rileyhgrant yes `git bisect` is a great debugging tool, one good reason to keep individual commits working and clean (as opposed to breaking something in one commit and fixing it three commits later but in the same PR for example) is that `git bisect` is much more useful if you can feel confident that your commits are generally clean.

**Comment by rileyhgrant** [comment]
I'm removing my assignment from this. This is a incredible niche bug that had been in production years before I joined the team, which is not to rid myself of blame, but is to say, if it has not been a problem yet, it likely will not be in the near future.

I'm removing my assignment to take this off my project board.

**Comment by rileyhgrant** [comment]
This is now relevant again, since v4 will have an updated Age Distribution Histogram.

In looking at the FAQ on prod, and in my local, this has been fixed by something else since we last looked at it.

![Screenshot 2023-10-23 at 13 11 11](https://github.com/broadinstitute/gnomad-browser/assets/59549713/3d800b3e-ec04-46d9-b4cc-111b01f168ba)

As such, closing this as completed.
